### ISSUE TITLE
subtitles/closed captions

### ISSUE THREAD

**Issue by AndrewRCD** [rrirower/DP2SceneGraphWizard#104]
I don't know if it is normal or not, so I am asking.
Can we add subtitles in multiple languages for the same video?
We can in the feed manager, but for some reason, when you build the SDK, it only shows the last entry.
If, for example, I add subs in EN, FR, and ES - on TV, it only shows the last entry, ES, and you don't have the option to select another sub.
If I change the order in the feed manager and add FR, ES, and EN, I can only see the EN sub.

With the upcoming update in October, when subs will be .....  well, kind of mandatory, I thought I try to see how it works :) 

Thanks

**Comment by rrirower** [comment]
Can you post your fed file that contains more than one subtitle so that I can test?

**Comment by AndrewRCD** [comment]
of course,
[subtest.json](https://github.com/rrirower/DP2SceneGraphWizard/files/14971225/subtest.json)

thank you

**Comment by rrirower** [comment]
Thanks, but, I need the actual url to the feed file.

**Comment by AndrewRCD** [comment]
Ah, let me put it our somewhere - i just made this for you - i used it on a channel I have submitted since and obviously ii deleted all the extra subs to have it work properly.

**Comment by rrirower** [comment]
Ok, that will work.  Having the url allows me to test while running the code.

**Comment by AndrewRCD** [comment]
sorry, I should have thought of that ......
https://05.hosting-allsuper.info/tests/subs/subtest.json

thank you

**Comment by rrirower** [comment]
OK, I've identified the bug and have a fi for it.  I'll have it in the next release.

**Comment by AndrewRCD** [comment]
you are awesome, thanks.

**Comment by rrirower** [comment]
Resolved in 1.0.0.2.
