### ISSUE TITLE
Episodes won't play

### ISSUE THREAD

**Issue by JLNjolo** [rrirower/DP2SceneGraphWizard#11]
If you click the play button the channel locks up. All other videos play.

**Comment by rrirower** [comment]
I'll need to know the url of your feed file so I can test. There may be something different about the way your series is defined.

**Comment by rrirower** [comment]
This appears to be a regression bug.  I will investigate further.  Check back later for an update.

**Comment by JLNjolo** [comment]
Thanks. One other question: Is there a way I can make the posters smaller like in the Roku sample channel?

________________________________

**Comment by rrirower** [comment]
Can you provide a sample of what you're describing in the Roku channel?  This project uses a grid layout.   It may not be able to support your request.

**Comment by JLNjolo** [comment]
Sure. The current channel shows smaller posters as in the attached "preview" and the channel itself. Your software channel shows larger posters.
________________________________

**Comment by JLNjolo** [comment]
Do you have a Paypal account? I would like to send you an offering.
________________________________

**Comment by rrirower** [comment]
> Sure. The current channel shows smaller posters as in the attached "preview" and the channel itself. Your software channel shows larger posters.

Can you provide a screen image of what you are seeing in the channel?  There was no attachment.

Donations are not required, but, are appreciated.  If you'd like to contribute to this project, please start the Wizard tool and click on the About button on the bottom right of the first screen.  You should see a donation button on the next screen.

**Comment by rrirower** [comment]
Fixed in version 1.0.0.0-alpha-4

**Comment by JLNjolo** [comment]
I followed the instructions, downloaded Alpha 4 and followed the Wizard,  but when I upload the newly created zip file I get this message.
________________________________

**Comment by rrirower** [comment]
There's no message attached.

**Comment by JLNjolo** [comment]
Apparently the attachment didn't come through. It was a screenshot that said this:
Application Received: 181587 bytes stored
Install Failure: Compilation Failed.PlayerTask
________________________________

**Comment by rrirower** [comment]
Please see issue #14

**Comment by JLNjolo** [comment]
That fixed the error issue but the initial one still exists even with the software update.
________________________________

**Comment by rrirower** [comment]
Fixed with latest zip file.
