### ISSUE TITLE
Sideload error 

### ISSUE THREAD

**Issue by rain-dotcom** [rrirower/DP2SceneGraphWizard#112]
<img width="1085" alt="Captura de Tela 2024-06-07 às 13 52 53" src="https://github.com/rrirower/DP2SceneGraphWizard/assets/172065401/c7e0333e-3ff2-4426-a123-b9adaaed478b">

this is the error
i try to slide the package

**Comment by rain-dotcom** [comment]
[IDDPMI PAJUIL TV.zip](https://github.com/user-attachments/files/15742864/IDDPMI.PAJUIL.TV.zip)

this is the package file

**Comment by rrirower** [comment]
Your manifest file shows a feed URL without an extension:

`FEED_URL=https://api.npoint.io/618ffb2a981f7d54c2aa`

Per the requirements of this project:

`NOTE: Your feed file MUST use an extension of '.JSON' or '.XML' and MUST conform to the Direct Publisher JSON and MRSS feed specifications AND define Category objects.`

This is so that the code knows how to parse your feed file.

**Comment by rain-dotcom** [comment]
ok
but i want to use your software 
i don't get it, did have  Tutorial video to host the channel

**Comment by rrirower** [comment]
What is it that you don't understand?  Perhaps reading some of the [discussions](https://github.com/rrirower/DP2SceneGraphWizard/discussions) or the [wiki](https://github.com/rrirower/DP2SceneGraphWizard/wiki) may help you.

**Comment by rain-dotcom** [comment]
okay 
please help me check this 
can this feed work for the package file 

https://nexolife.tv/rokutv/pajuiltv/pajuiltv.json

**Comment by rain-dotcom** [comment]
Hello???

**Comment by rrirower** [comment]
You can use the [Channel Fed Manager](https://github.com/rrirower/Channel-Feed-Manager) tool to validate your feed file.

**Comment by rain-dotcom** [comment]
<img width="779" alt="Elimar" src="https://github.com/rrirower/DP2SceneGraphWizard/assets/172065401/eeb62de8-dbf6-4958-a0b0-55000fc4e073">


hello
how can i change the channel text to white

**Comment by rrirower** [comment]
Please see the wiki for more info.

**Comment by rain-dotcom** [comment]
okay
please send me link to wiki

**Comment by rain-dotcom** [comment]
ok
![image](https://github.com/rrirower/DP2SceneGraphWizard/assets/172065401/36adc11c-020b-43c5-9d17-9f4c5298821c)
i get it
how can i save
can i use the notepad i use to open the code to save it, right

**Comment by rain-dotcom** [comment]
I have another question. I see that you released another version 9 hours ago. I already have the sftowear. Does the new release affect my sftowear?

or how can i update it to use new release

**Comment by rrirower** [comment]
You can use any editor to make changes. 

Each release of the software either fixes a bug, or, adds a new feature. You should make sure to keep up to date on the software by downloading and recreating your channel zip file.

**Comment by rain-dotcom** [comment]
okay
how can i change this play text 


![#FFFAFA](https://github.com/rrirower/DP2SceneGraphWizard/assets/172065401/209540e3-69d5-4b90-a4b8-a67201972036)

to my normal language spanish 
like this
<img width="1050" alt="Captura de pantalla 2024-06-09 a la(s) 15 10 34" src="https://github.com/rrirower/DP2SceneGraphWizard/assets/172065401/56a49726-607c-4532-b225-3e547a11021d">

**Comment by rrirower** [comment]
You'll need to scan through the source code in the zip file to locate those strings.  There's no other way at the moment.

**Comment by rain-dotcom** [comment]
<img width="1422" alt="Captura de pantalla 2024-06-11 a la(s) 20 04 07" src="https://github.com/rrirower/DP2SceneGraphWizard/assets/172065401/c47451ad-429d-40d2-a454-1080304a7ce6">
hello
please help me 
After i change the channel text colour 
the channel is not working again

**Comment by rain-dotcom** [comment]
[Zip 1111.zip](https://github.com/user-attachments/files/15795594/Zip.1111.zip)
this is file

**Comment by rrirower** [comment]
You need to upload the zip file before clicking the Install button.  Your zip file loaded correctly on my system:

![PXL_20240612_131904639 MP](https://github.com/rrirower/DP2SceneGraphWizard/assets/34550407/8714b58c-9043-4c9c-994e-40cc32b3aa84)

**Comment by rain-dotcom** [comment]
okay
thanks

**Comment by rain-dotcom** [comment]
![Annotation 2024-06-12 235841](https://github.com/rrirower/DP2SceneGraphWizard/assets/172065401/6451f407-6bf7-4f0d-b0ce-a22c837debd3)
but how can i change the style to normal 
i find it on font, i don't see it

**Comment by rain-dotcom** [comment]
![Annotation 2024-06-12 235841](https://github.com/rrirower/DP2SceneGraphWizard/assets/172065401/a8d50e21-b57a-4a11-bf02-a0d43509ec28)
and also how can i remove the playlist that show on the screen

**Comment by rrirower** [comment]
The `theme.json` file controls the font that is used throughout the code.  You need to change the font, or, add a new font to the theme.json file.  

You should consider using an editor like [Visual Studio Code](https://code.visualstudio.com) or something similar that allows you to search the code within the zip file.  Then search for "Playlist".  You are responsible for any changes you make within the source code.  If you're not comfortable changing source code, you should find an experienced person to make changes for you.

Lastly, I am working on making it easier to translate text in the source code.  There's no time frame when this will be available.

**Comment by rain-dotcom** [comment]
![WhatsApp Image 2024-06-15 at 19 00 49_c60620f3](https://github.com/rrirower/DP2SceneGraphWizard/assets/172065401/a262ba2a-7e6b-43ab-b157-3c60ee67fd89)

the is not publish

**Comment by rrirower** [comment]
You can use any editor to make changes. 

Each release of the software either fixes a bug, or, adds a new feature. You should make sure to keep up to date on the software by downloading and recreating your channel zip file.

**Comment by rrirower** [comment]
@ ferdiwerks Can you help this user?  I am currently away.

**Comment by ferdiworks** [comment]
@rain-dotcom How can I help? Just got notice that you may need help! Please explain the issue to me and provide the Feed file url and package you completed before enqrytion!

**Comment by rain-dotcom** [comment]
@ferdiworks
ok
i have test the package on my device and it work  
![WhatsApp Image 2024-06-12 at 17 35 58_a6180e83](https://github.com/rrirower/DP2SceneGraphWizard/assets/172065401/83cd4ec5-f275-4524-ae27-6caa9058582a)

so i i slideload the file and upload to my roku account this what it show
![WhatsApp Image 2024-06-15 at 19 00 49_c60620f3](https://github.com/rrirower/DP2SceneGraphWizard/assets/172065401/8cf47e17-d071-4fb7-ae6d-f6489ee12512)

**Comment by rain-dotcom** [comment]
this is the file
[Zoppp.zip](https://github.com/user-attachments/files/15855534/Zoppp.zip)

after slideload the file

**Comment by rrirower** [comment]
@ferdiworks thank you.

**Comment by ferdiworks** [comment]
@rain-dotcom First lets start at your json feed file!
Your feed is not formated correctly!
1)Your categories are not formated correctly on bottom of feed!
2)You classified the type as Movies and it should be tvSApecials - Why because you are using playlist and you do not need trickplay with tv specials and you do not have trickplay files or code attched in your feed so you need to use "tvSpecials" not "movies? and change your playlist categories to the following format: See two examples below

```
``}],"categories":[{
"name":"Snack TV",
"playlistName":"Snack TV",
"order":"manual"}],
"playlists":[{"name":"Snack TV",
"itemIds":["97784-22388-4286878","vt7LCaucEqe","97786-22390-4286880","JCHU0YEDdAK","97788-22392-4286882","97790-22394-4286884","97784-22388-4286878","97792-22396-4286888","97790-22394-4286884","97788-22392-4286882"]}]}

Or format like this code:

```
"categories":[{
"name":"3CTV",
"playlistName":"3CTV",
"order":"manual"},
{"name":"Island Vibez",
"playlistName":"Island Vibez",
"order":"manual"},{"name":"Rhythm & Soul",
"playlistName":"Rhythm & Soul",
"order":"manual"},
{"name":"Kool Kountry",
"playlistName":"Kool Kountry","order":"manual"},
{"name":"LIT",
"playlistName":"LIT",
"order":"manual"}],
"playlists":[{"name":"3CTV",
"itemIds":["97784-22388-4286878"]},
{"name":"Island Vibez",
"itemIds":["97786-22390-4286880"]},
{"name":"Rhythm & Soul",
"itemIds":["97788-22392-4286882"]},
{"name":"Kool Kountry",
"itemIds":["97790-22394-4286884"]},
{"name":"LIT",
"itemIds":["97792-22396-4286888"]}]}
```
```

**Comment by ferdiworks** [comment]
Your feed fle top should look like this:

`{"providerName":"MytvShow","lastUpdated":"2023-07-15T16:59:58+00:00","language":"en","liveFeeds":[],"tvSpecials":[{"id":"96488-19978-3177862","title":"Happy Birthday Mia Lamb","content":{"dateAdded":"2023-01-01T19:50:08+00:00","videos"`:

**Comment by rain-dotcom** [comment]
ok
i will change it

**Comment by rain-dotcom** [comment]
Thanks

**Comment by ferdiworks** [comment]
@rain-dotcom   Notice the id number for the video which is used in the playlist and categories on bottom!

**Comment by ferdiworks** [comment]
see full feed sample here:

`{"providerName":"MytvShow","lastUpdated":"2023-07-15T16:59:58+00:00","language":"en","liveFeeds":[],"tvSpecials":[{"id":"96488-19978-3177862","title":"Happy Birthday Mia Lamb","content":{"dateAdded":"2023-01-01T19:50:08+00:00","videos":[{"url":"https://c.themediacdn.com/link/hls/W3s3aS/iTeSM39sAwz/iG2HYpsWROA_1/playlist.m3u8","quality":"FHD","videoType":"HLS"}],"duration":6813,"validityPeriodStart":null,"validityPeriodEnd":null,"adBreaks":["00:10:00","00:22:00","00:34:00","00:46:00","00:58:00","01:10:00","01:22:00","01:34:00"]},"thumbnail":"https://2-web-shpcd1.streamhoster.com/e5ce/206408/mfrs/3177862/16819270.jpg?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vMi13ZWItc2hwY2QxLnN0cmVhbWhvc3Rlci5jb20vZTVjZS8yMDY0MDgvbWZycyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MTkwOTgxMTd9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=iB3jrkaLFnPFbY7G0mFzaEiSVt9A1gcMBYCgvn-sH0e3dUrwu9xHSLXk~fhjkW8yx-RfZIjd680H34t7r9tJmug73xAG5Kt395lKp2WkvT~j~1W5fP2pGHJfyDqI8Aa-Ta4vYiZGPx7wWEPOYSiY6qiMuayyX5O3Ad0~L~1oQ3ptMJ4adek2Nbp2M-luEHUEHXHM6eESwAeLaMwCg4-Rr8rSiG-RYzGBY9UwE9JL489f2il-j9m-IVZdpFVWGiCJnbivRqYYnSs~YqpdcHW1kmxKoAe7Xh7Jn32AhOTNgYKE4eyPBWLE5fFIgc3BF2ATNpLJ3IkXdUGe9QrT3rBgog__&Key-Pair-Id=APKAIQCJLWNYFADX6TFA","genres":["special"],"releaseDate":"2023-01-01T19:50:08+00:00","shortDescription":"Happy Birthday Mia Lamb","longDescription":"Happy Birthday Mia Lamb"},{"id":"96488-19978-3187480","title":"Your Video on TV for $20","content":{"dateAdded":"2021-09-01T12:38:07+00:00","videos":[{"url":"https://c.themediacdn.com/link/hls/W3s3aS/iTeSM39sAwz/iGgz3DsWO9C_1/playlist.m3u8","quality":"HD","videoType":"HLS"}],"duration":42,"validityPeriodStart":null,"validityPeriodEnd":null,"adBreaks":null},"thumbnail":"https://2-web-shpcd1.streamhoster.com/e5ce/206408/mfrs/3187480/16888896.jpg?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vMi13ZWItc2hwY2QxLnN0cmVhbWhvc3Rlci5jb20vZTVjZS8yMDY0MDgvbWZycyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MTkwOTgxMTd9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=iB3jrkaLFnPFbY7G0mFzaEiSVt9A1gcMBYCgvn-sH0e3dUrwu9xHSLXk~fhjkW8yx-RfZIjd680H34t7r9tJmug73xAG5Kt395lKp2WkvT~j~1W5fP2pGHJfyDqI8Aa-Ta4vYiZGPx7wWEPOYSiY6qiMuayyX5O3Ad0~L~1oQ3ptMJ4adek2Nbp2M-luEHUEHXHM6eESwAeLaMwCg4-Rr8rSiG-RYzGBY9UwE9JL489f2il-j9m-IVZdpFVWGiCJnbivRqYYnSs~YqpdcHW1kmxKoAe7Xh7Jn32AhOTNgYKE4eyPBWLE5fFIgc3BF2ATNpLJ3IkXdUGe9QrT3rBgog__&Key-Pair-Id=APKAIQCJLWNYFADX6TFA","genres":["special"],"releaseDate":"2021-09-01T12:38:07+00:00","shortDescription":"Get your Video on TV for $20","longDescription":"Get your Video on TV for $20 contact us at ondemandtvnetworks.com"},{"id":"96488-19978-3187518","title":"Carlos Maria 25th Anniversary","content":{"dateAdded":"2016-04-11T08:53:20+00:00","videos":[{"url":"https://c.themediacdn.com/link/hls/W3s3aS/iTeSM39sAwz/iGg3UesWOKU_1/playlist.m3u8","quality":"HD","videoType":"HLS"}],"duration":4258,"validityPeriodStart":null,"validityPeriodEnd":null,"adBreaks":["00:10:00","00:22:00","00:34:00","00:46:00","00:58:00"]},"thumbnail":"https://2-web-shpcd1.streamhoster.com/e5ce/206408/mfrs/3187518/16889262.jpg?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vMi13ZWItc2hwY2QxLnN0cmVhbWhvc3Rlci5jb20vZTVjZS8yMDY0MDgvbWZycyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MTkwOTgxMTd9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=iB3jrkaLFnPFbY7G0mFzaEiSVt9A1gcMBYCgvn-sH0e3dUrwu9xHSLXk~fhjkW8yx-RfZIjd680H34t7r9tJmug73xAG5Kt395lKp2WkvT~j~1W5fP2pGHJfyDqI8Aa-Ta4vYiZGPx7wWEPOYSiY6qiMuayyX5O3Ad0~L~1oQ3ptMJ4adek2Nbp2M-luEHUEHXHM6eESwAeLaMwCg4-Rr8rSiG-RYzGBY9UwE9JL489f2il-j9m-IVZdpFVWGiCJnbivRqYYnSs~YqpdcHW1kmxKoAe7Xh7Jn32AhOTNgYKE4eyPBWLE5fFIgc3BF2ATNpLJ3IkXdUGe9QrT3rBgog__&Key-Pair-Id=APKAIQCJLWNYFADX6TFA","genres":["special"],"releaseDate":"2016-04-11T08:53:20+00:00","shortDescription":"Carlos and Maria's 25th Anniversary","longDescription":"Carlos and Maria's 25th Anniversary"},{"id":"96488-19978-3187490","title":"ElizabethSweet16","content":{"dateAdded":"2015-11-08T11:49:38+00:00","videos":[{"url":"https://c.themediacdn.com/link/hls/W3s3aS/iTeSM39sAwz/iGgbcwsWO9y_1/playlist.m3u8","quality":"HD","videoType":"HLS"}],"duration":1472,"validityPeriodStart":null,"validityPeriodEnd":null,"adBreaks":["00:10:00"]},"thumbnail":"https://2-web-shpcd1.streamhoster.com/e5ce/206408/mfrs/3187490/16889152.jpg?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vMi13ZWItc2hwY2QxLnN0cmVhbWhvc3Rlci5jb20vZTVjZS8yMDY0MDgvbWZycyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MTkwOTgxMTd9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=iB3jrkaLFnPFbY7G0mFzaEiSVt9A1gcMBYCgvn-sH0e3dUrwu9xHSLXk~fhjkW8yx-RfZIjd680H34t7r9tJmug73xAG5Kt395lKp2WkvT~j~1W5fP2pGHJfyDqI8Aa-Ta4vYiZGPx7wWEPOYSiY6qiMuayyX5O3Ad0~L~1oQ3ptMJ4adek2Nbp2M-luEHUEHXHM6eESwAeLaMwCg4-Rr8rSiG-RYzGBY9UwE9JL489f2il-j9m-IVZdpFVWGiCJnbivRqYYnSs~YqpdcHW1kmxKoAe7Xh7Jn32AhOTNgYKE4eyPBWLE5fFIgc3BF2ATNpLJ3IkXdUGe9QrT3rBgog__&Key-Pair-Id=APKAIQCJLWNYFADX6TFA","genres":["special"],"releaseDate":"2015-11-08T11:49:38+00:00","shortDescription":"Happy Birthday Elizabeth","longDescription":"Happy Birthday, Elizabeth. Happy Sweet 16"}],"categories":[{"name":"Special Events","playlistName":"Special Events","order":"manual"}],"playlists":[{"name":"Special Events","itemIds":["96488-19978-3177862","96488-19978-3187480","96488-19978-3187518","96488-19978-3187490"]}]}`

**Comment by ferdiworks** [comment]
@rain-dotcom Once your feed is set correct it will display categories correctly and name them correctly!

The Software will comply with what it reads from the feed file!

Then you can seek and change your fonts in sofware code as @rrirower explained in an editor! Made backups of everything before edits!

Once done test by sideload, enqrypt and upload to Roku package!

**Comment by rain-dotcom** [comment]
hello 
thanks for your help

**Comment by rain-dotcom** [comment]
@ferdiworks
can  i use this code

i have make some change to the code

https://nexolife.tv/rokutv/33a2d9a1ce5df1b25f82.json

**Comment by ferdiworks** [comment]
@rain-dotcom = NO!
you cannot add categories after the closing brackets! Look at the sample I posted!
The provider code should be at top!\
And the label "movies" should be changed to tvSpecials, tvSpecials do not need trickplay files and all videosd need be "HLS" m3u8 videos which you already have listed!

**Comment by rain-dotcom** [comment]
okay

**Comment by rain-dotcom** [comment]
i think it okay now

{
  "providerName": "MytvShow",
  "lastUpdated": "2024-07-15T16:59:58+00:00",
  "language": "en",
  "liveFeeds": [],
  "tvSpecials": [
    {
      "id": "83b7270cbb564353b60caab36aea1d6f",
      "title": "IDDPMI PAJUIL TV",
      "content": {
        "dateAdded": "2024-01-01T19:50:08+00:00",
        "videos": [
          {
            "url": "https://96vd925eyxq7-hls-live.5centscdn.com/7413_push_2748_010/a00699b2893eb271017a361041555400.sdp/playlist.m3u8",
            "quality": "FHD",
            "videoType": "HLS"
          }
       ],
        "duration": 1211
      },
      "genres": [
        "documentary"
      ],
      "thumbnail": "https:\/\/i.vimeocdn.com\/video\/1867795389-878467d3137d1a482673f663d80dcf11a37f1c10537b6ca47d9eaca041851511-d_800x450",
      "releaseDate": "2018-05-08",
      "shortDescription": "Drone flying over the real Noah's ark site October 2017.",
      "longDescription": "Canal oficial de la Iglesia de Dios Pentecostal MI en PAJUIL.",
      "tags": [
        "live"
      ]
    },
    {
      "id": "9b1d302d9a0a4b5380cfd1d7102efbe3",
      "title": "El Poder del Espíritu Santo y la Misión- IDDPMI PAJ",
      "content": {
        "dateAdded": "2024-09-01T12:38:07+00:00",
        "videos": [
          {
            "url": "https://player.vimeo.com/external/953232443.m3u8?s=4821148a3aaa7d4326f1b9f1eef6bc0afba470d8",
            "quality": "HD",
            "videoType": "HLS"
          }
        ],
        "duration": 1539
      },
      "genres": [
        "documentary"
      ],
      "thumbnail": "https:\/\/i.vimeocdn.com\/video\/1867793316-e11f8a8742d5a95d60ac43369ba3ddfb5c06c7ce2eea397264a2d2d698c97cb4-d_800x450",
      "releaseDate": "2024-05-08",
      "shortDescription": "TEl Poder del Espíritu Santo y la Misión- IDDPMI PAJUI",
      "tags": [
        "VOD"
      ]
    },
    {
      "id": "23268c8943bc4f6ebdc040a5525f8be9",
      "title": "Honrando a las madres",
      "content": {
        "dateAdded": "2024-04-11T08:53:20+00:00",
        "videos": [
          {
            "url": "https://player.vimeo.com/external/953232418.m3u8?s=16ed517d5e8a3473ba31510ff40b15ba87c8b394",
            "quality": "HD",
            "videoType": "HLS"
          }
        ],
        "duration": 1507
      },
      "genres": [
        "documentary"
      ],
      "thumbnail": "https:\/\/i.vimeocdn.com\/video\/1867793316-e11f8a8742d5a95d60ac43369ba3ddfb5c06c7ce2eea397264a2d2d698c97cb4-d_800x450",
      "releaseDate": "2018-05-08",
      "shortDescription": "Honrando a las madres - Culto especial - IDDPMI PAJUIL.",
      "tags": [
        "VOD"
      ]
    },
    
    {
      "id": "20f7279f919245769e1c344797cf8dc0",
      "title": "Llamados a servir",
      "content": {
        "dateAdded": "2024-04-11T08:53:20+00:00",
        "videos": [
          {
            "url": "https://player.vimeo.com/external/953232390.m3u8?s=208e77300511ee846d1970eb95843c03504f9b91",
            "quality": "HD",
            "videoType": "HLS"
          }
       ],
        "duration": 1744
      },
      "genres": [
        "documentary",
        "educational"
      ],
      "thumbnail": "https:\/\/i.vimeocdn.com\/video\/1867793316-e11f8a8742d5a95d60ac43369ba3ddfb5c06c7ce2eea397264a2d2d698c97cb4-d_800x450",
      "releaseDate": "2019-02-02",
      "shortDescription": "Llamados a servir - IDDPMI PAJUIL. ",
      "tags": [
        " VOD"
      ]
    },
    
    {
      "id": "6f3da5310be74ec6aec31b19cf04ce3b",
      "title": "Culto de adoracio",
      "content": {
        "dateAdded": "2024-04-11T08:53:20+00:00",
        "videos": [
          {
            "url": "https://player.vimeo.com/external/953232360.m3u8?s=17ea8da2d6329118057cdfa5a0753906a14139ba",
            "quality": "HD",
            "videoType": "HLS"
          }
        ],
            "duration": 856,
            "language": "en-US"
          },
          "thumbnail": "https:\/\/i.vimeocdn.com\/video\/1867793316-e11f8a8742d5a95d60ac43369ba3ddfb5c06c7ce2eea397264a2d2d698c97cb4-d_800x450",
          "episodeNumber": 12,
          "releaseDate": "2019-11-26",
          "shortDescription": "Culto de adoración - IDDPMI PAJUIL."
        },
    
    {
      "id": "fd42bfb10d46485f84547a778f0e782e",
      "title": "¿Cómo manejar el _desá",
      "content": {
        "dateAdded": "2024-11-08T11:49:38+00:00",
        "videos": [
          {
            "url": "https://player.vimeo.com/external/953232330.m3u8?s=1f440a27a3133323a0b1289d755ccf30bf32a76a",
            "quality": "HD",
            "videoType": "HLS"
          }
        ],
        "duration": 1472,
        "validityPeriodStart": null,
        "validityPeriodEnd": null,
        "adBreaks": [
          "00:10:00"
        ]
      },
      "thumbnail": "https:\/\/i.vimeocdn.com\/video\/1867793316-e11f8a8742d5a95d60ac43369ba3ddfb5c06c7ce2eea397264a2d2d698c97cb4-d_800x450",
      "genres": [
        "VOD"
      ],
      "releaseDate": "2015-11-08T11:49:38+00:00",
      "shortDescription": "¿Cómo manejar el _desá",
      "longDescription": "¿Cómo manejar el _desánimo__ - IDDPMI PAJ"
    }
  ],
  "categories": [
    {
      "name": "STREAMING / EN VIVO",
      "query": "STREAMING / EN VIVO",
      "order": "manual"
    },
    
     {
      "name": "NUESTROS VIDEOS",
      "query": "NUESTROS VIDEOS",
      "order": "manual"
    }
  ],
  "playlists": [
   {
      "name": "STREAMING / EN VIVO",
      "itemIds": [
        "83b7270cbb564353b60caab36aea1d6f",
   ]
    },
   
         {
      "name": "NUESTROS VIDEOS",
      "itemIds": [
        "9b1d302d9a0a4b5380cfd1d7102efbe3", "23268c8943bc4f6ebdc040a5525f8be9", "20f7279f919245769e1c344797cf8dc0","6f3da5310be74ec6aec31b19cf04ce3b", "fd42bfb10d46485f84547a778f0e782e"
        
      ]
    }
  ]
}

**Comment by ferdiworks** [comment]
@rain-dotcom I cannot promiser you that your Queries will work with the mixing of playlist! You sent back a Category list that to my knowledge will not work, When it comes to categories you need to decide to use Query or playlist., I gave you samples of categories with playlist and you returned something different from what I suggested! Roku doers have a feed validator you can look up and test your feed! 

However I can only suggest what I know what works and tell you the why of it working!
I do not believe mixing Query and playlist in your category code will work, I can be wrong I am not perfect and maybe @rrirower knows better than me!

I suggest you look back at my sample code and follow the code for non Query as I suggested!

Then you can test the feed in a channel package!

**Comment by rrirower** [comment]
You can mix categories based on a query or a playlist in your code. The best way to do this is by using the software I commented about above.  The channel feed manager tool can manage your feed file to accomplish this.

**Comment by ferdiworks** [comment]
@rain-dotcom Use the json feed validator to check ur feed file!
[](https://www.jsonschemavalidator.net)

If it is correct and validates then you are good to go!!

**Comment by rrirower** [comment]
@rain-dotcom the JSON feed validator is a good way to validate JSON syntax.  However, it will not catch logic errors in your feed file.  To check for logic errors, you can use the Channel Feed Manager to validate for errors.

**Comment by rain-dotcom** [comment]
![Annotation 2024-06-21 171842](https://github.com/rrirower/DP2SceneGraphWizard/assets/172065401/6e59b510-2460-41ac-8277-43389502048f)
I try to install the software, it say error

**Comment by rain-dotcom** [comment]
Thank you
i find the error and i fix it
the problem is not with my feed url
the problem is with deep link i Add i have fix the error and my channel is working now
