### ISSUE TITLE
Search on large feed files do not work

### ISSUE THREAD

**Issue by wajidbux** [rrirower/DP2SceneGraphWizard#114]
**Describe the bug**

Search on large feed files does not work. the channel hangs and is booted out to the home screen.

![Screenshot 2024-07-31 171254](https://github.com/user-attachments/assets/f987c367-0036-4cc3-bcb0-5fd173664f95)

**Comment by rrirower** [comment]
Do you have RAF enabled? 
What version are you running?

**Comment by wajidbux** [comment]
running the latest version with RAF enabled. smaller feed files work perfectly well.

**Comment by rrirower** [comment]
Can you provide the URL to the feed file that fails, and, the search term that causes the failure?

**Comment by wajidbux** [comment]
https://movielandroku.dreamhosters.com/roku.json

You can search for any title that shows up on the grid screen.

**Comment by samadtehrani** [comment]
Looks like you have around 2000 videos. I have 23000. Your .json file is under 2Mb, mine is 13Mb. But my channel is working perfectly. It's slow on loading time, so I added an animation to cover that, but overall it's working correctly.

**Comment by rrirower** [comment]
@wajidbux When I open your feed file in the Channel Feed Manager, I see lots of these warnings...

```
{ "time": "2024-08-01 10:05:28.2016", "level": "WARN", "message": "Item 'Jabberwocky' defines tags, but, a category that associates those tags could not be found." }
{ "time": "2024-08-01 10:05:28.2016", "level": "WARN", "message": "Item 'Chandler' defines tags, but, a category that associates those tags could not be found." }
{ "time": "2024-08-01 10:05:28.2016", "level": "WARN", "message": "Item 'Spasmo' defines tags, but, a category that associates those tags could not be found." }
{ "time": "2024-08-01 10:05:28.2016", "level": "WARN", "message": "Item 'Satan’s Black Wedding' defines tags, but, a category that associates those tags could not be found." }
{ "time": "2024-08-01 10:05:28.2016", "level": "WARN", "message": "Item 'Criminally Insane' defines tags, but, a category that associates those tags could not be found." }
{ "time": "2024-08-01 10:05:28.2016", "level": "WARN", "message": "Item 'The Plunderers' defines tags, but, a category that associates those tags could not be found." }

```

I'm not sure yet if this would cause a problem.  I suspect it would.  But, the code should not crash either.  I'll need to look into it further.

I'm in the middle of some development, so, I won't be able to dig in for a few days.

**Comment by wajidbux** [comment]
can you test with another feed URL https://movielandroku.dreamhosters.com/roku.json and see if the problem persists

**Comment by rrirower** [comment]
The second feed file you posted causes a Timeout Exception.  I'm not sure why since that code runs in a Task thread.
@samadtehrani Are you seeing this error?  You have many more channel items.

**Comment by wajidbux** [comment]
sorry I gave the same URL once again,  https://movielandroku.dreamhosters.com/roku1.json

**Comment by rrirower** [comment]
Same result....Execution timeout.

**Comment by wajidbux** [comment]
there have been some errors that I have overlooked while working with 1.0.0.0-beta5. I get many errors in my analytics dashboard under channel health
[Channel Health 2024-08-01T2039.pdf](https://github.com/user-attachments/files/16458458/Channel.Health.2024-08-01T2039.pdf)

**Comment by wajidbux** [comment]
> Same result....Execution timeout.

smaller feed files work with ease, they dont take much time in loading as well.

**Comment by wajidbux** [comment]
> I'll need to look into this further. I'm not sure why you are the only one with these issues. Either that, or, I'm not getting appropriate feedback from other users.

sure, take your time i was just highlighting a few problems. there is also a bug in your latest channel feed manager, the search feed does not generate. do u want me to mark it as a bug under CFM?

**Comment by rrirower** [comment]
Yes.  Please use the CFM issues bug report.  Please be specific in describing the problem.

**Comment by rrirower** [comment]
Yes.  There has been some progress made on this.  It should be resolved with the next version.  If you'd like, I can test it with the URL of your feed file.  Attach the url here if you want me to test.

**Comment by wajidbux** [comment]
wp-smart tv feed- https://movielandroku.dreamhosters.com/roku.json
CFM feed- https://hookup.dreamhosters.com/roku.json

> Yes. There has been some progress made on this. It should be resolved with the next version. If you'd like, I can test it with the URL of your feed file. Attach the url here if you want me to test.

wp-smart tv feed- https://movielandroku.dreamhosters.com/roku.json
CFM feed- https://hookup.dreamhosters.com/roku.json

Do keep in mind the search feature for large feed files.

Thank you.

**Comment by rrirower** [comment]
I was able to get your channel to load and play with ads. I should have a new version soon.

**Comment by wajidbux** [comment]
Are any updates releasing soon?

**Comment by rrirower** [comment]
Yes.  Unfortunately, I had to recover from a hardware failure and rebuild from backups.  I'm trying to get a new version out this week.

**Comment by wajidbux** [comment]
Any updated version being released soon.

**Comment by rrirower** [comment]
Yes ... Unfortunately, life gets in the way and testing bugs causes delays. 

Soon ....

**Comment by rrirower** [comment]
This should be fixed with the latest release.
