### ISSUE TITLE
DP2SceneGraphWizard issues

### ISSUE THREAD

**Issue by sarabeni** [rrirower/DP2SceneGraphWizard#12]
i create packages on DP2SceneGraphWizard tool but after the channel black

MY question

is a way to add background image

**Comment by rrirower** [comment]
You should be able to adjust the branding of your channel in the developer dashboard.  That would include adding a background image.

**Comment by ferdiworks** [comment]
I don;t see an option in version 3 to add a background image only add background color!

**Comment by sarabeni** [comment]
Please what is the solution to Add background to SDK 

can we do that through rss feed

please help?

**Comment by rrirower** [comment]
As I stated earlier, you can specify a background image in the developer dashboard.  Go to Manage my channels/Branding.  You should see:

![Capture](https://github.com/rrirower/DP2SceneGraphWizard/assets/34550407/3585c945-84a8-4fdf-92c2-715417ac3999)

**Comment by sarabeni** [comment]
sorry  branding is not in SDK dashboard

it Only available in Direct channel
![tf6r](https://github.com/rrirower/DP2SceneGraphWizard/assets/142458019/89cd502e-4583-46fc-8d57-2cec96420643)
![tgt76t67 r76](https://github.com/rrirower/DP2SceneGraphWizard/assets/142458019/6af27ca5-e120-4bd0-99a4-15a4155729c1)

**Comment by rrirower** [comment]
Sorry for the confusion.  I have not converted my channel yet, so, when I go to 'my channels', I see the DP dashboard.  There is no SDK dashboard for me.

The existing wizard code does not support a background image.  If you want to submit it as an enhancement issue request, fee free.  I can't promise a quick response as I am still developing the code to support Ads and Subscriptions.

**Comment by ferdiworks** [comment]
I found a way to add background image to the output template!

**Comment by ferdiworks** [comment]
> Sorry for the confusion. I have not converted my channel yet, so, when I go to 'my channels', I see the DP dashboard. There is no SDK dashboard for me.
> 
> The existing wizard code does not support a background image. If you want to submit it as an enhancement issue request, fee free. I can't promise a quick response as I am still developing the code to support Ads and Subscriptions.

Note: the wizard tool source file does support background image!
in components/MainScene.brs line# 5
m.top.backgroundUri = "pkg:/images/background.jpg"

background image name = background.jpg
image size of background image you place in image folder = 1920 X 1080
image format jpeg image = jpg

**Comment by ferdiworks** [comment]
@rrirower you can add these changes to the source files and close this isuue!

**Comment by fronderblash** [comment]
hello [ferdiworks](https://github.com/ferdiworks) please something like this right 
![gvyjvvvvvvvv](https://github.com/rrirower/DP2SceneGraphWizard/assets/141512200/f059e6a3-c1ff-4659-a2d2-487311f5f6cd)

**Comment by ferdiworks** [comment]
> hello [ferdiworks](https://github.com/ferdiworks) please something like this right ![gvyjvvvvvvvv](https://user-images.githubusercontent.com/141512200/261872154-f059e6a3-c1ff-4659-a2d2-487311f5f6cd.jpg)

Note: I already created the Snack TV SDK for the client a few weeks ago! There was also another member here click SDK issue for other members post doing same channel, And another person email me for sdk for this channel so there may be a conflict of interest with snack tv channel and owner!

**Comment by rrirower** [comment]
@ferdiworks @fronderblash please continue this discussion offline.
