### ISSUE TITLE
Roku DRM email

### ISSUE THREAD

**Issue by JLNjolo** [rrirower/DP2SceneGraphWizard#121]
"You are receiving this email because you have one more apps that use PlayReady DRM for content protection. Roku will be ending support for PlayReady DRM in the United States, Canada, and Latin America in the near future. To ensure uninterrupted service for your customers, you should migrate your app's content protection to Widevine DRM by June 30, 2025."

I rely on your software for my channel building and wondered if you had anything in the works that would assist with this new Roku requirement. This tech blurb can be confusing.

Thanks.

**Comment by rrirower** [comment]
I did some research and contacted some other Roku folks.  Here's the reply:

```
If you aren't using DRM then this doesn't apply

The change is that if you are using PlayReady, then you need to switch. Basically, PlayReady is being deprecated. If you're not using PlayReady (for whatever reason, incl. not using any DRM), then you're all good
```

Basically, if you don't use DRM (Digital Rights Management) for your videos, you're in the clear.  Nothing to do.

**Comment by JLNjolo** [comment]
Thanks.
________________________________
