### ISSUE TITLE
Sideload get's error?

### ISSUE THREAD

**Issue by ferdiworks** [rrirower/DP2SceneGraphWizard#13]
A few times when sideloading output file I got an  error:  parse error for mainloader xml 

Reran the software and tried again with a new zip file and was good!

Any ideas what causes this?

**Comment by rrirower** [comment]
Sounds like a Roku error.  My guess is that the device was not ready when it was asked to sideload the channel zip.

**Comment by ferdiworks** [comment]
A system software and update worked with the Roku device and the errors stopped!
