### ISSUE TITLE
V4 video play issue

### ISSUE THREAD

**Issue by ferdiworks** [rrirower/DP2SceneGraphWizard#15]
Ok so we got Verion 4 to load after adding line to manifest
bs_libs_required=roku_ads_lib

Channel now siseloads but video player has issues!

Videos open but stay in loading then freeze!

**Comment by rrirower** [comment]
Are you side loading a package or zip?  I tested with a zip and it appeared to work fine. Is it a specific type of feed content that hangs?

**Comment by ferdiworks** [comment]
Nothing special, I tested it with my tvSpecials feed and I tested one of my client feeds who has movies series and shortform videos, Alpha 3 runs with no issues on those feeds nut Alpha 4 video play keeps loading and freezes on those test and a few others. I see your coder changes and looked at it, it loasd if we add the line to manifest so the sideload error goers away but them that playe of the video freezes!

**Comment by rrirower** [comment]
Can you provide a URL for me to test with?

**Comment by ferdiworks** [comment]
OK this is one of my tvSpecials channels I tried w version 3 and 4
works well w V# video freezes V4

https://c.themediacdn.com/feed/W3s3aS/iTtnaWjsAtP/OlOBqr3si46?format=rokujson

**Comment by rrirower** [comment]
Thanks. I'll test and report back.

**Comment by rrirower** [comment]
Can you provide a list of the steps you used to side-load the code?  I want to walk through your steps since the application works when I install it from a zip file.

**Comment by rrirower** [comment]
I think I found the problem.  It appears that somehow I zipped the wrong version of the code.  I must have zipped the Ads version I am working on instead of the correct one.  That's why you had to add that line to the manifest. 

I am preparing to package a new zip.

**Comment by fronderblash** [comment]
ok

**Comment by rrirower** [comment]
@ferdiworks Can you take a look at the attached zip and let me know if it resolves the issues?  You should not need to add any lines to your manifest.  If this works, I will repost it.

[DPtoSceneGraph.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12386423/DPtoSceneGraph.zip)

**Comment by ferdiworks** [comment]
That zip did not load, Application Received: 224924 bytes stored.
Install Failure: No manifest. Invalid package. I'll try and test again!

**Comment by ferdiworks** [comment]
I unzip the zip sent and the manifest file is gone but I will add one and test it!

**Comment by ferdiworks** [comment]
OK added manifest file zipped it loaded it and freezes at load

**Comment by ferdiworks** [comment]
I was curious and tried it with the Ad Libs line in mainfest and without and both froze at loading!

**Comment by rrirower** [comment]
Can you provide the steps you are using when you test?  I need to figure out why the code works for me and not you.

**Comment by ferdiworks** [comment]
OK i will do a screen record just cant capture the Roku load!

**Comment by ferdiworks** [comment]
I sidseload the zip you sent and it froze!
I created the manuifest with your tool software then copied it over to the zip you sent!

Note version 3 works just fine no problems but v43 has the issue.

Here is the video screen record

https://www.loom.com/share/4db425dcc4164fcfb85612254a8867ef?sid=79f9c812-38da-406c-9883-4c5cb978f836

**Comment by ferdiworks** [comment]
@rrirower You wrote: Can you provide the steps you are using when you test? I need to figure out why the code works for me and not you.

1) I used the software to create test channel
2)Copied manifest over to the zip you suplied!
3)Zipped it
6_sideloaded the zip
7)Roku open on screen and froze at loading!
8) Updated software on Roku device, Restarted system, tried again! Same result!
9_Retested  V3 with edits from me and all loaded good!
10) Changed feed with new manifest file and your zip provided and it froze again!
11) Tried the V4 again with zip from version 4 output
Application Received: 219610 bytes stored.
Install Failure: Compilation Failed.PlayerTask
add line ad libs loads fine!

**Comment by rrirower** [comment]
Thanks for the video.  Unfortunately, it ended right at the time you were to upload the zip file, so, I did not get to see the error.  Additionally, I used the URL you posted above and the one in your video and both opened and played on my Roku.  I sideloaded the zip and both played correctly.

I used the code from the DPtoSceneGraph.zip file posted above and updated the manifest to use your URL.  I tested from within my debugger and by sideloading the zip file.

**Comment by rrirower** [comment]
Here's my test:


https://github.com/rrirower/DP2SceneGraphWizard/assets/34550407/fd06d970-c753-439b-b0b2-2e9329b7c357

![PXL_20230820_145329520 MP](https://github.com/rrirower/DP2SceneGraphWizard/assets/34550407/ba717501-26ab-434a-a0c5-976cfb5e0ce0)

**Comment by fronderblash** [comment]
Hello Am sorry for interrupt

please can 
[HpD.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12388478/HpD.zip)
you help me to test this file also

**Comment by rrirower** [comment]
@fronderblash The zip file you posted contains corrupt code as I indicated [above](https://github.com/rrirower/DP2SceneGraphWizard/issues/15#issuecomment-1685028626).  If you'd like to test with a potential fix, download the [zip](https://github.com/rrirower/DP2SceneGraphWizard/issues/15#issuecomment-1685068513) I posted above for Joe, and add your manifest to the zip file.  Then, sideload the zip.

**Comment by ferdiworks** [comment]
@rrirower I watch your video and seen the install failure and I seen in the debugger window the ad libs line in therter! I see the image posted above from one of my feeds! Thanks for your patience and support! I support the project and what you are doing here! I keep trying and testing, sorry my video cut off as my monitor is a Roku TV and when it laurnches unless I capture w a second camera or phone record i dont get the second video to edit into one!

**Comment by ferdiworks** [comment]
@rrirower I don't understand as well, I am  more seasoned working w SDK files and working w coding and have published many sites for myself and clients over the years! I keep tedsting your files and will report back!  I don't know why I get the a difference from your test! I tried another device and tested again ensuring system updates and restarts to devixces and computer!

**Comment by rrirower** [comment]
@ferdiworks Can you try the following:

- Download the zip I posted above.
- Add your manifest to the zip.
- Sideload the zip.

You do not need to re-run the Wizard tool since there were no changes to the tool.

**Comment by ferdiworks** [comment]
@fronderblash I tested your zip and get same errors as my own w version 4 and with the zip given here and your feed, Your feed works w version 3 just fine!

What I don't understand is why 3 different people here in the issues section  keep asking for this snack tv channel help even after I myself was hired and produced a fully working SDK Channel with my own sdk template and script.

**Comment by fronderblash** [comment]
[rrirower](https://github.com/rrirower)

thanks it worked 
![Screenshot 2023-08-20 at 10 56 29 AM](https://github.com/rrirower/DP2SceneGraphWizard/assets/141512200/2d9698bc-a2a4-4065-85e1-512352ebed71)

**Comment by rrirower** [comment]
@ferdiworks I'm still not sure what error you are getting.  Can you take a picture of the screen, or, something like that?  I'd liek to release this updated version if I can resolve this issue.

**Comment by rrirower** [comment]
@ferdiworks As you can see from his post, @fronderblash got his channel to work with the updated zip above.  Please double-check your steps.

**Comment by ferdiworks** [comment]
@rrirower I just tested his zip posted and ran the test and got same errors I am now taking and redownloading the Dp to scenegraph zip again and going to test it again!

**Comment by rrirower** [comment]
@ferdiworks His zip was corrupt. I gave him the steps to follow above to test with the new zip.

**Comment by fronderblash** [comment]
it show this thing 
![wddddddddd](https://github.com/rrirower/DP2SceneGraphWizard/assets/141512200/b8cbca2d-2ea9-4245-9504-d019c793d321)

![wddddddddd](https://github.com/rrirower/DP2SceneGraphWizard/assets/141512200/dd0f3703-544c-4600-a48f-cc5f2a956e9f)

**Comment by rrirower** [comment]
@ferdiworks I've seen that message if your manifest is missing a FEED_URL line or it is commented out with "#".

**Comment by ferdiworks** [comment]
@rrirower I know this lol
I am not new to this!
I just tried this again and again and what i get is the same error that fronerblash just reported! Over and over with many manifest changes from different working channels!
He just posted an image asnd thats what I get!

**Comment by rrirower** [comment]
I apologize if I've offended either of you, but, please understand the frustrating aspects of trying to resolve this.  It's been difficult trying to get clear info about the problem.

Can either of you provide your manifest file so I can test with it?

Are you side-loading the zip, or, a package.

Lastly, can either of you post the zip that fails for you so I can try to load it?

**Comment by fronderblash** [comment]
[Uploading DPtoSceneGraph (5).zip…]()

**Comment by fronderblash** [comment]
[DPtoSceneGraph (5).zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12388649/DPtoSceneGraph.5.zip)

**Comment by ferdiworks** [comment]
here is a test channel w same error he repoted as well
https://ondemandtvservices.net/source.zip

**Comment by ferdiworks** [comment]
> I apologize if I've offended either of you, but, please understand the frustrating aspects of trying to resolve this. It's been difficult trying to get clear info about the problem.
> 
> Can either of you provide your manifest file so I can test with it?
> 
> Are you side-loading the zip, or, a package.
> 
> Lastly, can either of you post the zip that fails for you so I can try to load it?

YOU HAVE NOT OFFENDED ME!

I support the project and don't mind testing the templates or software! I have some expeirence so I believe I can contribute and help!

**Comment by ferdiworks** [comment]
> it show this thing ![wddddddddd](https://user-images.githubusercontent.com/141512200/261863983-b8cbca2d-2ea9-4245-9504-d019c793d321.jpg)
> 
> ![wddddddddd](https://user-images.githubusercontent.com/141512200/261863953-dd0f3703-544c-4600-a48f-cc5f2a956e9f.jpg)

This is the same error I been reporting all along!

**Comment by fronderblash** [comment]
ok

**Comment by rrirower** [comment]
I found the bug by looking into your individual zip files.  These should fix it.  Please let me know so I can post an updated zip.

[ferdiworks.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12388739/ferdiworks.zip)
[fronderblash.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12388740/fronderblash.zip)

**Comment by ferdiworks** [comment]
> I found the bug by looking into your individual zip files. These should fix it. Please let me know so I can post an updated zip.
> 
> [ferdiworks.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12388739/ferdiworks.zip) [fronderblash.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12388740/fronderblash.zip)

That zup worked and loaded, Now I will test it w other feeds!

**Comment by fronderblash** [comment]
yes it work

> I found the bug by looking into your individual zip files. These should fix it. Please let me know so I can post an updated zip.
> 
> [ferdiworks.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12388739/ferdiworks.zip) [fronderblash.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12388740/fronderblash.zip)

**Comment by ferdiworks** [comment]
@rrirower Ok testing with other feeds and adding background image works weell for me now!

**Comment by fronderblash** [comment]
ok

**Comment by fronderblash** [comment]
[ferdiworks](https://github.com/ferdiworks)
please how did you add background images

**Comment by fronderblash** [comment]
[rrirower](https://github.com/rrirower)
[ferdiworks](https://github.com/ferdiworks)
Thanks for your  help
but

how can i change this image to my own image 
![rdtdtr](https://github.com/rrirower/DP2SceneGraphWizard/assets/141512200/22594606-d6a4-496d-b2ed-4b6a8a6d3410)

**Comment by ferdiworks** [comment]
> [rrirower](https://github.com/rrirower) [ferdiworks](https://github.com/ferdiworks) Thanks for your help but
> 
> how can i change this image to my own image ![rdtdtr](https://user-images.githubusercontent.com/141512200/261868352-22594606-d6a4-496d-b2ed-4b6a8a6d3410.jpg)

You can use photoshop or another photo editor

**Comment by rrirower** [comment]
Thanks to you both for helping.  I will be posting a new zip shortly.
