### ISSUE TITLE
Series - play all bug or issue

### ISSUE THREAD

**Issue by ferdiworks** [rrirower/DP2SceneGraphWizard#18]
**Series - play all bug or issue**

The zip file you sent back to me has been tested on many feeds and works with the exception of one issue or bug!

Let me explain: If I go in and go direct to a series and select it, I then get the option to Play all or click to list episodes!
if you click Play all the screen freezes up and you can't get out of it without going to the home button!
If you play anything at all before clicking a series and then play all = the play all works and starts the videos!

I tried a few feeds when I discovered this issue or bug and get the same results
Attached is the zip you sent back to me with a small feed that I tested after testing larger feeds and get the same results!

[ferdiworks.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12415078/ferdiworks.zip)

**Comment by ferdiworks** [comment]
I found a fix. On the Details brs page. I changed the "Play All" to "Play" and it plays now!

**Comment by rrirower** [comment]
This will be fixed in the next release.
