### ISSUE TITLE
Missing .exe?

### ISSUE THREAD

**Issue by DerekWongMI** [rrirower/DP2SceneGraphWizard#19]
The zip file I downloaded only contain the components, images, and source folders, reading your Wiki looked like it's an executable file, am I missing something here?

**Comment by rrirower** [comment]
Go to the [release](https://github.com/rrirower/DP2SceneGraphWizard/releases) page.  If you've downloaded alpha-4, you'll see that the release included changes to the BrightScript code and not the Wizard code.  So, if this is your first time using the wizard, you'll need to download a prior version (alpha-3) and install it.  Then, run the Wizard.  It will download the alpha-4 zip you probably downloaded.  You should then be up to date.
