### ISSUE TITLE
Works great!  Small nuances

### ISSUE THREAD

**Issue by DaveBarnitz** [rrirower/DP2SceneGraphWizard#21]
Hey thanks a lot for this. Worked pretty well for me even on first attempt.  Just a few small nuances I came across:

1. Whenever I go back to try to submit it again, in the software, to open and search for any of the content images to upload (from my PC), the Windows popup browser seems to default to search for a .json feed, and  I don't have a way to toggle it back to 'All Files', so nothing comes up in search. It might be a Windows thing, some sort of cache but wondering if that came up with anyone else. I'm on Win11, and the fix is just restarting my PC.

2.  Any chance of getting more customizeable colors, hex decimal codes. We seem limited to only a handful of colors.  I saw in the forum comments you were looking to add background images, which would be great.

3. I still have the 'Roku Rowing Channel' at the  top of my channel?   I did enter my channels name in the software, and I looked in the Manifest and few other files and didn't see a place to change this.

Anyway thanks again!  It working great and was pretty quick to do (albeit, I've done a few attempts tweaking things).

**Comment by rrirower** [comment]
I just posted a new release (1.0.0.0-alpha-5).  You should update with the latest.

**Comment by ferdiworks** [comment]
@DaveBarnitz I think you should try this version Alpha5 as I been testing it all day and I think you will be happy w the results!
