### ISSUE TITLE
package slideload error

### ISSUE THREAD

**Issue by Awero877** [rrirower/DP2SceneGraphWizard#24]
Hello, I want to express my gratitude for this tool; it performed admirably on my first attempt. However, I did come across a few minor issues:

The problem I'm encountering with my package is...

I used your tool to create the package, and it worked flawlessly on my device.

After creating the package, I sideloaded it on my device, generated the Roku package, and submitted it for publishing. However, when I checked my channel, I encountered errors. Instead of displaying my videos, it only shows my background.

Could you kindly assist me with this matter? Here is the package I'm referring to: 
[BB zip (2).zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12568331/BB.zip.2.zip)

**Comment by rrirower** [comment]
Your feed file does not contain Category objects.  Please read the [Prerequisites](https://github.com/rrirower/DP2SceneGraphWizard) for using this tool.  

Additionally, you are using the alpha-5 version.  Alpha-6 was released yesterday.  Please 'watch' this repo if you want notification of new releases.

**Comment by Awero877** [comment]
Hello [rrirowe](https://github.com/rrirower)

Thank you for your response.

Yes, my feed includes C
![ffs](https://github.com/rrirower/DP2SceneGraphWizard/assets/144604760/5b4e58b5-9c80-44a3-8ab0-e523621e6fbd)
![teee](https://github.com/rrirower/DP2SceneGraphWizard/assets/144604760/030bd345-dfdf-4b92-8442-1989b13aa13c)
ategory objects, and I'm using Alpha-6. I've verified that there's nothing wrong with my feed.

Here's the issue: The package works after uploading it via sideload. However, after sideloading it on Roku, generating the encrypted package, and uploading it to my Roku account for publishing, I encountered an error when I checked my TV.

To help diagnose the problem, could you please sideload the package I sent, generate an encrypted package on Roku, upload it to your Roku account, and go back to your roku device
[BTV CHANNEL (1).zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12568678/BTV.CHANNEL.1.zip)
 (the one you used for sideloading)? You will likely encounter the same error.

Thank you."

**Comment by rrirower** [comment]
@Awero877 Sorry, but, I don't currently have the time to debug your channel as I am trying to continue development of this product.  Perhaps @ferdiworks can assist you.  He's successfully used this tool to publish plenty of channels.

While your channel feed does define Category objects, you use 'tags' for your content.  The tags do not relate to any defined Category.  More importantly, your Playlists use duplicate content ids.   I question the validity of your feed file.  Please use the Channel Feed Manager on on this site to validate your content.

**Comment by ferdiworks** [comment]
@Awero877 Sorry I was away this past week but You can send me a link to my email at admin@ondemandtvnetworks.com and I will look at your package and feed.

**Comment by ferdiworks** [comment]
@Awero877 OK I got your email. I was able to package and upload the channel to my Roku account without error!
I have seen some issues like this in the Roku forums. You may need to contact partner success art Roku!
Your channel works fine and I added it as a beta channel

https://my.roku.com/account/add?channel=NHVKTM

**Comment by fronderblash** [comment]
Ok thanks  
I have added the link and it works

But can you send me the package file you generate if it works on my developer account

**Comment by ferdiworks** [comment]
**@fronderblash** This was for **Awero877**

**Comment by fronderblash** [comment]
Yes but I can benefit from the package

**Comment by ferdiworks** [comment]
@fronderblash How would an encrypted package benefit you? Awero877 can send you the channel zip package if he wants to! I don't have the right to share his files!
