### ISSUE TITLE
Warning while compiling

### ISSUE THREAD

**Issue by comporder1** [rrirower/DP2SceneGraphWizard#25]
Latest version gives warning while compiling on the roku device...

BRIGHTSCRIPT: WARNING: unused variable 'episode' in function 'initsections' in pkg:/components/EpisodesScreen/SeasonsWithEpisodesScreen.brs(29)

I do not have any content with seasons/episodes to test with. The warning may not be an issue.

**Comment by rrirower** [comment]
It's not an issue. It's in a function I have not fully implemented yet and may remove.
