### ISSUE TITLE
Error trying to side load Version 1.0.0.0-alpha-7

### ISSUE THREAD

**Issue by adamesq** [rrirower/DP2SceneGraphWizard#39]
I'm getting "Install Failure: Compilation Failed.PlayerTask" when trying to install a channel created today with the alpha-7 version. I created it with the feed I made in Channel Feed Manager last night. I added items to the feed today.

I do see that the feed now generates some kind of error, so maybe CFM is doing something odd? 

I then side loaded the same channel created with Alpha-6 last night. It side loaded with no issue with content from the same feed.

Please let me know if I can provide more info.

**Comment by rrirower** [comment]
I'll need the url for your feed.  I won't be able to look at it until tomorrow.

**Comment by adamesq** [comment]
Sure - and thank you - http://silverwerks.tv/r/silverwerksfeed.json

**Comment by rrirower** [comment]
Can you post the manifest from your package?

**Comment by adamesq** [comment]
Sure - I added a couple more notes above as well.

```
# Channel Details
# Auto-generated by DPtoSceneGraph wizard version 1.0.0.0-alpha-7
# (c) Copyright 2023, Michael Harnad, All rights reserved.
# Support at https://github.com/rrirower

# NOTE: Uppercase attributes are CUSTOM.

title=Silverwerks
major_version=1
minor_version=0
build_version=0
FEED_URL=https://silverwerks.tv/r/silverwerksfeed.json
splash_color=#000000
BACKGROUND_COLOR=#000000
ui_resolutions=hd
USE_RAF=0
OFFER_SUBSCRIPTIONS=0
supports_input_launch=1
mm_icon_focus_hd=pkg:/images/channel.png
splash_screen_hd=pkg:/images/splash.jpg
OVERHANG=pkg:/images/overhang.png
BACKGROUND_IMAGE=pkg:/images/background.jpg
```

**Comment by adamesq** [comment]
Roku feed validator returned: Roku Search Feed 2.0 Validation Result: Failure
“no assets downloaded”
The feed is loading in the channel I had created with Alpha 6 (when the feed had less in it…one of the objects I had changed today from a TV Special to a TV Series, of that helps. Only one episode is in there so far).

**Comment by rrirower** [comment]
It's a bug.  It only happens if you don't use RAF.  I should have it fixed tomorrow.

**Comment by adamesq** [comment]
OK - Rare that it's not on my end. 😂 

Should I post about the Channel Feed Manager feed validation (and dropping genres) issues mentioned above in the GitHub?

**Comment by adamesq** [comment]
...and THANK YOU.

**Comment by rrirower** [comment]
I'm already aware of the genres bug. I have a fix for it.

**Comment by rrirower** [comment]
Alpha-7.2 was uploaded today.  Please re-run the wizard to create your channel.  Additionally, in testing your channel, you have some categories that contain no content.

Please re-test and let me know how you make out.

**Comment by rrirower** [comment]
There's still a compilation problem.  It works in debug, but, not when sideloaded.  Working on it.

**Comment by rrirower** [comment]
Alpha-7.3 was uploaded to fix the compilation error.
Let me know if it fixes your issues.

**Comment by adamesq** [comment]
👍🏻 on Alpha 7.3. (Now I want to go figure out creating an ad feed.)
HOWEVER, while the feed validates with the CFB Tool, it fails in the JSON schema validator and with Roku's feed validator. 

Inside of CFB the tool to generate a search feed gives me: Fatal
Program exception detected: "IsonManager.SeriesObject' does not contain a definition for 'content" in method 'AppendSearchFeed".

Here's the one I tested: https://silverwerks.tv/r/silverwerksfeed-manualfix.json
I tried removing the categories you had mentioned (just haven't added the content that goes there to the feed yet). I had to do this manually b/c when a category is removed (trashed), save feed doesn't actually save the change. Also, I added the version tag since the JSON Schema Validator caught that it was missing from the CFB generated feed.

Roku's feed validator:
The following errors and warnings were encountered:
no assets downloaded

The JSON Schema Validator:
Required properties are missing from object: assets.
Schema path: #/required

**Comment by rrirower** [comment]
I'll be uploading a new CFM soon that will fix that problem and some others.

**Comment by adamesq** [comment]
GREAT! I've got the channel submitted for the shift from DP!👏🏻
Is there something I can add to the feed to deal with the "no assets downloaded" error? Side loaded channel is running fine and I got all ✅ in the Dashboard.

**Comment by rrirower** [comment]
Is that message from a Search feed?  Where do you see it?

**Comment by adamesq** [comment]
![Screenshot 2023-10-02 at 12 00 53 PM](https://github.com/rrirower/DP2SceneGraphWizard/assets/34196956/ee79ae7e-4817-4f1d-b708-9612c692d3e8)

**Comment by rrirower** [comment]
Please see the [Roku manifest](https://developer.roku.com/docs/developer-program/getting-started/architecture/channel-manifest.md) doc. You must comply with its image requirements.

**Comment by rrirower** [comment]
Have you resolved your image issue?

**Comment by adamesq** [comment]
Hi @rrirower - I had already submitted the channel. It was (of course) on my end...I used a 1920x1080 image. Still published. Thank you!
