### ISSUE TITLE
RAF integration throws and error

### ISSUE THREAD

**Issue by wajidbux** [rrirower/DP2SceneGraphWizard#45]
Hi Michael I have been testing your D2P SGW and I must say you have done a fantastic job. Everything works perfectly well but I ran into an error while trying to implement RAF in my project. the error is shown below
![error-wizard](https://github.com/rrirower/DP2SceneGraphWizard/assets/54876296/f27bde13-3246-428e-a6d1-c1a33b5f92dc)
my feed URL https://mangatv.dreamhosters.com/roku.json

My vast Tag https://tag.targeting.unrulymedia.com/rmp/215278/0/vast3?devId=ROKU_ADS_TRACKING_ID&w=ROKU_ADS_DISPLAY_WIDTH&h=ROKU_ADS_DISPLAY_HEIGHT&appbundle=ROKU_ADS_APP_ID&appname=MangaTv&appid=ROKU_ADS_APP_ID&useragent=ROKU_ADS_USER_AGENT&appstoreurl=https://channelstore.roku.com/details/74ee7ec3bfa16bcad8c368cd7f229dc8&cntlen=ROKU_ADS_CONTENT_LENGTH&dnt=ROKU_ADS_LIMIT_TRACKING&timestamp=ROKU_ADS_TIMESTAMP
( this tag i have been using this in DP for more than 3 years and there has been no such problem.)
Hope you find the time to look into it.
Thank you in advance and keep up the good work.

**Comment by rrirower** [comment]
What version are you running?  Please look into main.brs at the top.

**Comment by rrirower** [comment]
I think I may know what the problem is.  The code makes a call to get your ad pods and receives nothing.  I'm not sure why that is.  I'll need to dig deeper.

**Comment by rrirower** [comment]
Ad server URLs without macros work fine.  I'm not sure, but, I think I may need the values of the macros in your server url so that they can be substituted at run time.

**Comment by wajidbux** [comment]
> What version are you running? Please look into main.brs at the top.

' BrightScript code version 1.0.0.0-alpha-7.3
' https://github.com/rrirower

**Comment by rrirower** [comment]
I'm not sure. But, it may help to see what they gave you. I'm just not sure why the URL does not work as is.  

If they gave you any instructions, I'd like a peek at that also.

**Comment by wajidbux** [comment]
> I'm not sure. But, it may help to see what they gave you. I'm just not sure why the URL does not work as is.
> 
> If they gave you any instructions, I'd like a peek at that also.

Your tag for Magna TV is listed below:

[https://tag.targeting.unrulymedia.com/rmp/215278/0/vast3?devId=[INSERT_MACRO]&w=[INSERT_MACRO]&h=[INSERT_MACRO]&appbundle=[INSERT_MACRO]&appname=[INSERT_MACRO]&appstoreurl=[INSERT_MACRO]&cntlen=[INSERT_MACRO]&cntcat=[INSERT_MACRO]&cntepisode=[INSERT_MACRO]&cntgenre=[INSERT_MACRO]&cntlan=[INSERT_MACRO]&cntseries=[INSERT_MACRO]&cnttitle=[INSERT_MACRO]&us_privacy=[INSERT_MACRO](https://tag.targeting.unrulymedia.com/rmp/215278/0/vast3?devId=%5bINSERT_MACRO%5d&w=%5bINSERT_MACRO%5d&h=%5bINSERT_MACRO%5d&appbundle=%5bINSERT_MACRO%5d&appname=%5bINSERT_MACRO%5d&appstoreurl=%5bINSERT_MACRO%5d&cntlen=%5bINSERT_MACRO%5d&cntcat=%5bINSERT_MACRO%5d&cntepisode=%5bINSERT_MACRO%5d&cntgenre=%5bINSERT_MACRO%5d&cntlan=%5bINSERT_MACRO%5d&cntseries=%5bINSERT_MACRO%5d&cnttitle=%5bINSERT_MACRO%5d&us_privacy=%5bINSERT_MACRO)]

Insert URL parameter macros as per Roku documentation.

**Comment by rrirower** [comment]
Thanks. I'll let you know when I have a resolution.

**Comment by wajidbux** [comment]
> Thanks. I'll let you know when I have a resolution.

I should be the one thanking you for taking the time to find a resolution.

**Comment by wajidbux** [comment]
> Can you ask your ad provider if the url they provided you will work with client-side ad stitching?

I believe it is for client-side since I have been using these tags with direct publisher for more than 3 years now.

**Comment by rrirower** [comment]
I downloaded the [Roku Stream Tester](http://devtools.web.roku.com/stream_tester/html/index.html) app and ran it with some ad server URLs.  They worked fine.  When I loaded your ad server URL it did not return any ads.  I think you should contact the ad server company and explain the issue to them.

**Comment by wajidbux** [comment]
> I downloaded the [Roku Stream Tester](http://devtools.web.roku.com/stream_tester/html/index.html) app and ran it with some ad server URLs. They worked fine. When I loaded your ad server URL it did not return any ads. I think you should contact the ad server company and explain the issue to them.

I have contacted them now I have to wait several days for a response from them. By the way, when will your subscription model be available to test and use?

**Comment by rrirower** [comment]
Funny you should ask.  I'm looking for someone to help with that. I have no plans to convert my channel. I contacted Roku and asked if I could set up a test user for subscriptions and they told me I had to go through the process of setting up monetization. It's too involved for me especially since I'm not converting.

So, I was going to post on the forum looking for a user who could set up a test user for me. There's no time frame on subscriptions until I get help.

**Comment by wajidbux** [comment]
> Funny you should ask. I'm looking for someone to help with that. I have no plans to convert my channel. I contacted Roku and asked if I could set up a test user for subscriptions and they told me I had to go through the process of setting up monetization. It's too involved for me especially since I'm not converting.
> 
> So, I was going to post on the forum looking for a user who could set up a test user for me. There's no time frame on subscriptions until I get help.

I have many test accounts and I am happy to help at any time but the subscription model is greyed out no matter how much I try to toggle it on it does
not work so I assumed you had disabled the function, adding a screenshot below.
![sub](https://github.com/rrirower/DP2SceneGraphWizard/assets/54876296/b768498d-f685-47f3-b9eb-ca2dce72ad67)

**Comment by rrirower** [comment]
Yes, it is disabled until the code is in place.  I appreciate your offer.  I may take you up on it after I get the next release out hopefully this weekend.

**Comment by wajidbux** [comment]
> Yes, it is disabled until the code is in place. I appreciate your offer. I may take you up on it after I get the next release out hopefully this weekend.

Happy to help, let me know when the code is ready.

**Comment by ferdiworks** [comment]
Has anyone been successful with using V8 to create, upload, and publish a channel with Ads? I have been waiting and watching to see the results before I create and try to publish my own channel with Ads!

**Comment by rrirower** [comment]
@ferdiworks you may get a response by posting on the Roku forum.

**Comment by rrirower** [comment]
@wajidbux Have you been able to make any progress on this?  Additionally, I'd like to take you up on the offer to help with subscriptions.  Please read the discussion '[Subscription Help Needed](https://github.com/rrirower/DP2SceneGraphWizard/discussions/31)'.

**Comment by wajidbux** [comment]
> @wajidbux Have you been able to make any progress on this? Additionally, I'd like to take you up on the offer to help with subscriptions. Please read the discussion '[Subscription Help Needed](https://github.com/rrirower/DP2SceneGraphWizard/discussions/31)'.

Hi Michael,
No progress yet since the advertising company has not yet responded. Regarding the subscription model, I have a demo channel and test user along with 2 test products. 
Send me the code if it is ready to be tested.

**Comment by rrirower** [comment]
Thanks, but, that won't work for me. I need to be able to step through the code so I can debug. That means I'll need the credentials you set up for the test user (user name and products you set up).  I may need other info, but, I won't know until I start debugging.  I've just started designing the code.

If you can still help, great. If not, no worries.

**Comment by wajidbux** [comment]
> Thanks, but, that won't work for me. I need to be able to step through the code so I can debug. That means I'll need the credentials you set up for the test user (user name and products you set up). I may need other info, but, I won't know until I start debugging. I've just started designing the code.
> 
> If you can still help, great. If not, no worries.

I can give you whatever you need for debugging and testing purposes. But I would suggest you should go through this article to be more clear.
https://developer.roku.com/en-gb/docs/developer-program/roku-pay/testing/billing-testing.md

**Comment by rrirower** [comment]
Thanks. I'll get back with you this coming week when I'm ready for testing.

**Comment by rrirower** [comment]
Can you provide me with the url of the feed file for test channel?

**Comment by rrirower** [comment]
Just for giggles, I tried running some partial test code and quickly realized I am not going to be able to do this with your help.  I think I'm going to have to take the monetization plunge even though I'm not progressing any further.  I'll let you know if I need any more help.

**Comment by rrirower** [comment]
This is getting way too complicated for my pay grade.  I've tried to progress through the payout stuff on Roku, but, had to stop.  It's simply overkill since have no intention of using any of it. I'm going to have to rethink my approach to testing this.

**Comment by wajidbux** [comment]
> This is getting way too complicated for my pay grade. I've tried to progress through the payout stuff on Roku, but, had to stop. It's simply overkill since I have no intention of using any of it. I'm going to have to rethink my approach to testing this.

You are a genius, nothing is impossible for you.

**Comment by rrirower** [comment]
Can you provide me with the feed URL you have for the test channel? I don't think I'll be able to debug, but, I want to give it a try. I think it will look at my account and not yours.

**Comment by wajidbux** [comment]
> Can you provide me with the feed URL you have for the test channel? I don't think I'll be able to debug, but, I want to give it a try. I think it will look at my account and not yours.

sure, the feed URL is- https://mangatv.dreamhosters.com/roku.json. it has both movies and series.

**Comment by rrirower** [comment]
Can you give me some insight into the test products you set up?  I ran through the code and it appeared to contain a catalog of two or three items.  I'm not sure if it's valid because I don't know the particulars of the video products you set up.  Can you provide a list or screenshot of what products you defined?

**Comment by rrirower** [comment]
I've made contact with one of the developers of the BrighterScript language and he provided some instructions on how I might debug my code.  It will boil down to your comfort level with making technical changes.  Since I don't know your technical expertise, let me know if you're not comfortable with any of this.

In order for me to test my code, I would need to run it on your Roku box.  I should be able to accomplish this if you make some temporary changes to your network router and provide me with the actual IP address of the Roku box.  if you're ok with this, let me know.  If not, that's ok too.

In the meantime, I've decided to continue the process of signing up for monetization although I've run into some problems and don't know how far I'll get.  The entire process seems to be pretty klugy.

**Comment by wajidbux** [comment]
> I've made contact with one of the developers of the BrighterScript language and he provided some instructions on how I might debug my code. It will boil down to your comfort level with making technical changes. Since I don't know your technical expertise, let me know if you're not comfortable with any of this.
> 
> In order for me to test my code, I would need to run it on your Roku box. I should be able to accomplish this if you make some temporary changes to your network router and provide me with the actual IP address of the Roku box. if you're ok with this, let me know. If not, that's ok too.
> 
> In the meantime, I've decided to continue the process of signing up for monetization although I've run into some problems and don't know how far I'll get. The entire process seems to be pretty klugy.

Sorry for the late reply, I was traveling. I'm ok with just let me know what you require from my side.
by the way, I managed to figure out the problem, there was nothing wrong with the code. I had very little traffic that's why the vast tags could not generate data to parse. now it's working fine but I ran into a problem with the keys i lost the keygen both dev id and password. will email partner success and find a possible solution

**Comment by rrirower** [comment]
@wajidbux thanks for the update.  I actually have some subscription code that's nearing testing.

I wanted to ask if you use a subscription backend processing now. If so, can you explain the workflow?

**Comment by wajidbux** [comment]
> @wajidbux thanks for the update. I actually have some subscription code that's nearing testing.
> 
> I wanted to ask if you use a subscription backend processing now. If so, can you explain the workflow?

No, all my channels are ad-based, but I wanted to try out a channel, and compare the different monetization options and which is more profitable.
