### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fronderblash** [rrirower/DP2SceneGraphWizard#48]
hello am getting error after click downloads
**Version number:**
 - Version [e.g. 1.0.0.0-alpha-8]

![Annotation 2023-10-25 053631](https://github.com/rrirower/DP2SceneGraphWizard/assets/141512200/c111755f-cbae-499f-9d81-953a0db3959c)

**Comment by rrirower** [comment]
This is a bug with the wizard.  I'll need to investigate further.

**Comment by fronderblash** [comment]
okay

**Comment by rrirower** [comment]
I should have a new version by the end of today.

**Comment by ferdiworks** [comment]
@fronderblash Was this Folder you entered for the desktop an empty folder directory? And not a directory you want to create?

**Comment by rrirower** [comment]
Fixed in 1.0.0.0-alpha-8.1.

**Comment by rrirower** [comment]
@fronderblash Does alpha-8.1 resolve your issue?

**Comment by fronderblash** [comment]
No

**Comment by fronderblash** [comment]
![Annotation 2023-10-27 060024](https://github.com/rrirower/DP2SceneGraphWizard/assets/141512200/1ae83e71-902a-420f-ac83-b0f67e4d99ba)

**Comment by rrirower** [comment]
@fronderblash 'access denied' is a permissions error.

Make sure you uninstalled the previous release before installing 8.1.

Make sure the download folder you selected is valid and not protected.

Make sure you are not editing any of the files that are downloaded while running the wizard.

**Comment by rrirower** [comment]
I've re-run the installer and it works fine.

**Comment by rrirower** [comment]
@fronderblash Have you resolved this?

**Comment by rrirower** [comment]
@fronderblash have you resolved this?

**Comment by rrirower** [comment]
No response from the user. Closed.
