### ISSUE TITLE
no thumbnails showing on sideloaded app, but videos play fine

### ISSUE THREAD

**Issue by mdenhardt** [rrirower/DP2SceneGraphWizard#50]
i successfully used rdp-to-scenegraph-channel-template to convert from direct publisher to scenegraph, currently awaiting publishing, in reviewing how to get my videos back in categories, not just one row i found this program - i used your  json feed manager in the past - a big help!

i used the conversion program, and sideloaded the zip - i see my categories, and videos play, but the thumbnails of videos do not show, if i scroll around it does change and i can play all. Is there a step i'm missing or do i need to update using VScode? i've opened the brs files in vscode, but fumbling through them now.

Secondly when i use the direct publisher json feed on your version or rdp-to-scenegraph-channel-template, the feed never loads, but using a mrss feed works fine. I see the thumbnails on the basic template, not this one though. Attached is my mrss feed, if i copy a thumb into a browser i see the picture so i know the pictures are viewable
[8.xml.txt](https://github.com/rrirower/DP2SceneGraphWizard/files/13288702/8.xml.txt)

thank you for any help

**Comment by rrirower** [comment]
Are the thumbnails not showing on the JSON or XML feed?  If JSON, can you post your feed file?

**Comment by ferdiworks** [comment]
@mdenhardt

**Try to change the heade**r

<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:media="http://search.yahoo.com/mrss/" xmlns:atom="http://www.w3.org/2005/Atom" version="0">

**Change to:**

<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:media="http://search.yahoo.com/mrss/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">

looking at your feed I found first you list the categories for all videos two times

**Example:** 
 <media:category>All Videos</media:category>
      <media:category>All Videos</media:category>

**You need to remove the double categories and list it once!**

**Next Your links** are missing the trailing slash
"https://player.vimeo.com/external/493867443.hd.mp4?s=bfd77dbbfc6c92954e5f6c63e56ddf23d9538a64&amp;profile_id=175" duration="5469">

**should look like this:**
"https://player.vimeo.com/external/493867443.hd.mp4?s=bfd77dbbfc6c92954e5f6c63e56ddf23d9538a64&amp;profile_id=175" duration="5469"/>

****and** the image links have a space at the end by trailing slash**
<media:thumbnail url="https://storage.googleapis.com/mariancdn/thumbnails/exp_Angels.jpg" />

**should look like this:**
<media:thumbnail url="https://storage.googleapis.com/mariancdn/thumbnails/exp_Angels.jpg"/>

**Next Change the Title of your channe**
<channel>
    <title>FireTv Export From Roku Json</title>

**change to channel name**
<channel>
    <title>My Channel Name</title>

**See if that helps you!**
Joe Ferdinando

**Comment by ferdiworks** [comment]
**Header change to version 2.0**
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:media="http://search.yahoo.com/mrss/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">

**Comment by mdenhardt** [comment]
sorry, i gave you a copy of a fresh "Channel host manager" xml, that one
didn't have the title changed.
this version, which is the actual one running on my sideloaded app does the
same thing
https://storage.googleapis.com/mariancdn/6.xml

the live version of the json - direct publisher file is:
https://storage.googleapis.com/mariancdn/rokufeed6.json
the thumbnails show fine there, and the xml file is derived from that json,
using the utility

at your suggestion i added the slash to the file name, but i did not see
the space in the thumbnail image line, so i made no changes to those lines

thank you!

**Comment by ferdiworks** [comment]
@mdenhardt 
I don't understand why you didn't use that same JSON feed file link in your SDK Package. It looks good to me!

**Comment by mdenhardt** [comment]
when i use json feed, nothing at all loads, just the background image. the json works fine in the directpublisher live app

i was half wrong, my sideloaded app was running https://storage.googleapis.com/mariancdn/8.xml

which has the wrong app title
https://storage.googleapis.com/mariancdn/6.xml does the same thing as the json, no feed - just splash screen and bg image

**Comment by mdenhardt** [comment]
are you suggesting this?

# Channel Details
# Auto-generated by DPtoSceneGraph wizard version 1.0.0.0-alpha-8.1
# (c) Copyright 2023, Michael Harnad, All rights reserved.
# Support at https://github.com/rrirower

# NOTE: Uppercase attributes are CUSTOM.

bs_libs_required=roku_ads_lib
title=The Divine Mercy
major_version=2
minor_version=0
build_version=0
FEED_URL=https://storage.googleapis.com/mariancdn/rokufeed6.json
#splash_color=#9B0000
BACKGROUND_COLOR=#000000
ui_resolutions=sd,hd,fhd
USE_RAF=0
OFFER_SUBSCRIPTIONS=0
supports_input_launch=1
mm_icon_focus_hd=pkg:/images/channel.png
splash_screen_hd=pkg:/images/splash.png
BACKGROUND_IMAGE=pkg:/images/background_image.png

# Optional settings.  To use, uncomment.
#USE_THUMBNAIL_BACKGROUND=true
#TEXT_COLOR=#000000

**Comment by mdenhardt** [comment]
are you suggesting this for manifest?
`# Channel Details
# Auto-generated by DPtoSceneGraph wizard version 1.0.0.0-alpha-8.1
# (c) Copyright 2023, Michael Harnad, All rights reserved.
# Support at https://github.com/rrirower

# NOTE: Uppercase attributes are CUSTOM.

bs_libs_required=roku_ads_lib
title=The Divine Mercy
major_version=2
minor_version=0
build_version=0
FEED_URL=https://storage.googleapis.com/mariancdn/rokufeed6.json
#splash_color=#9B0000
BACKGROUND_COLOR=#000000
ui_resolutions=sd,hd,fhd
USE_RAF=0
OFFER_SUBSCRIPTIONS=0
supports_input_launch=1
mm_icon_focus_hd=pkg:/images/channel.png
splash_screen_hd=pkg:/images/splash.png
BACKGROUND_IMAGE=pkg:/images/background_image.png

# Optional settings.  To use, uncomment.
#USE_THUMBNAIL_BACKGROUND=true
#TEXT_COLOR=#000000`

**Comment by ferdiworks** [comment]
@mdenhardt Yes take that zip file and sideload it and test it again

**Comment by mdenhardt** [comment]
using json nothing loads, other than the bg image and splash screen, no content for me to move around.  
that is the same behavior when i used rdp-to-scenegraph-channel-template

i simplified an mrss feed
https://storage.googleapis.com/mariancdn/7.xml - it loads the one video, shows the 2 categories, but the thumbnail is just a transparent box, and no description is shown

**Comment by ferdiworks** [comment]
@mdenhardt I am going to take another look at your JSON Feed

**Comment by rrirower** [comment]
You've got some errors in your JSON feed file. 

1. Language is required for content types.  Especially if you plan on using captioning.

2. You've got a mismatch with your Categories and Playlists.  

A category is based on either a query or a playlist.  Your feed file defines only one category that's derived from a playlist, yet, you have 5 playlist objects defined.  The code is stopping because it doesn't know what to do with the "All" playlist.  There is no associated category.  You should take a deep dive into your Categories and Playlists.

**Comment by mdenhardt** [comment]
> You've got some errors in your JSON feed file.
> 
> 1. Language is required for content types.  Especially if you plan on using captioning.
> 2. You've got a mismatch with your Categories and Playlists.
> 
> A category is based on either a query or a playlist. Your feed file defines only one category that's derived from a playlist, yet, you have 5 playlist objects defined. The code is stopping because it doesn't know what to do with the "All" playlist. There is no associated category. You should take a deep dive into your Categories and Playlists.

i understand, but i'm certain thats not whats wrong with the thumbnails not showing, i created a simple mrss feed, and tried the thumbnail with 3 different urls, and i still dont see any thumbnails

https://storage.googleapis.com/mariancdn/7.xml

**Comment by rrirower** [comment]
Your XML feed file does not conform with the [Roku MRSS feed spec](https://developer.roku.com/docs/specs/direct-publisher-feed-specs/mrss-dp-spec.md#mediathumbnail). It looks like it's from an RSS feed.

As stated on the first page of this project, the feed file must conform to the Roku spec(s) in order for the wizard-generated code to process it.

**Comment by ferdiworks** [comment]
@mdenhardt Ok I done some edits to your categories and playlist in the JSON feed, replace with this code:
```
`"categories": [
    {
      "name": "All Videos",
     "playlistName":"All",
      "order": "most_popular"
    },
    {
      "name": "Divine Mercy Matters",
      "playlistName":"Divine Mercy Matters",
      "order": "chronological"
    },
    {
      "name": "Discovering the Diary",
      "playlistName":"Discovering the Diary",
      "order": "most_recent"
    },
    {
      "name": "Featured Free for a Limited Time",
      "playlistName": "Featured Free",
      "order": "manual"
    },
    {
      "name": "Explaining the Faith with Fr. Chris Alar",
      "playlistName":"Explaining the Faith",
      "order": "chronological"
    }
  ],
  "playlists": [
    {
      "name": "All",
      "itemIds": [
        "archives-srfaustina1",
        "c8168fc591444f1a8dd57f6066c26c88",
        "01915b3a171a461ebe6e0a098d53e705",
        "2c27a33b4eee4705971b1904490c72be",
        "91d627fdd4dc4dc0a79737cfc5a89428",
        "c9cdab6e098c403a86f776cf13cd68d2",
        "55c605228e584bc6ad3788b754808943",
        "d0f01326bd764b6991b4e8ad165f2c59",
        "39946711a4b5461d9519797a95e09de4",
        "4471a6ab89c444a6ac624fc6ebb69341",
        "0236fd9efc0a4be090b1130526b86880",
        "8cb5b158c6ae403f9ced68af25aabe73",
        "e13adc59658e483fa519f0dca3bcd30a",
        "b2672956cd6044158b2a9187291f6afa",
        "3f5aab9529084f32bd02e901d9ff53b9",
        "235b85bd90844a05865190a0fca659ff"
      ]
    },
    {
      "name": "Divine Mercy Matters",
      "itemIds": [
        "c8c1e4b00b144a649887cccf124522c5"
      ]
    },
    {
      "name": "Discovering the Diary",
      "itemIds": [
        "01915b3a171a461ebe6e0a098d53e705",
        "4471a6ab89c444a6ac624fc6ebb69341",
        "c8168fc591444f1a8dd57f6066c26c88"
      ]
    },
    {
      "name": "Featured Free",
      "itemIds": [
        "f1377ac9543c4b9795239516ef0caa64",
        "38f3697469b4418b82fbb59945ed4aaa"
      ]
    },
    {
      "name": "Explaining the Faith",
      "itemIds": [
        "8cb5b158c6ae403f9ced68af25aabe73",
        "d708716987934c26add6574788ea4117",
        "06e25536ff004058a6453fd86ab1930e",
        "22af8f6370434cf887072b1c7a27a4f8",
        "39946711a4b5461d9519797a95e09de4",
        "e13adc59658e483fa519f0dca3bcd30a",
        "d0f01326bd764b6991b4e8ad165f2c59",
        "2c27a33b4eee4705971b1904490c72be",
        "1c606116194c4f73a32b5d4e6f696fb0",
        "91d627fdd4dc4dc0a79737cfc5a89428",
        "c9cdab6e098c403a86f776cf13cd68d2",
        "55c605228e584bc6ad3788b754808943",
        "0236fd9efc0a4be090b1130526b86880",
        "b2672956cd6044158b2a9187291f6afa",
        "3f5aab9529084f32bd02e901d9ff53b9",
        "84633bc134db49fdbd1075d827581810",
        "e82af69af78a464d8acf8ff0fa6ac775",
        "a0ab3f8ce2854a7a8680ebadfd289452",
        "f3a0024758b148a081df0e2513b270c8",
        "3c2bf497896b4f3eab22d3bf6e239bee",
        "b46997f173374cf2910e0a2b56d68f1c",
        "8322cd8277164eb981f4be57f1438df0"
      ]
    }
  ]
}
```

**Comment by mdenhardt** [comment]
one interesting thing i've finally figured out, using the 1 video test xml -  if i use the header suggested by @ferdiworks 
```
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:media="http://search.yahoo.com/mrss/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
```

nothing shows at all on the home screen

if i use header
```
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:dcterms="http://purl.org/dc/terms/" xmlns:media="http://search.yahoo.com/mrss/" xmlns:atom="http://www.w3.org/2005/Atom" version="0">
```

i at least see the outline and can play the video

**Comment by mdenhardt** [comment]
> @mdenhardt Ok I done some edits to your categories and playlist in the JSON feed, replace with this code:
> 
> ```
> `"categories": [
>     {
>       "name": "All Videos",
>      "playlistName":"All",
>       "order": "most_popular"
>     },
>     {
>       "name": "Divine Mercy Matters",
>       "playlistName":"Divine Mercy Matters",
>       "order": "chronological"
>     },
>     {
>       "name": "Discovering the Diary",
>       "playlistName":"Discovering the Diary",
>       "order": "most_recent"
>     },
>     {
>       "name": "Featured Free for a Limited Time",
>       "playlistName": "Featured Free",
>       "order": "manual"
>     },
>     {
>       "name": "Explaining the Faith with Fr. Chris Alar",
>       "playlistName":"Explaining the Faith",
>       "order": "chronological"
>     }
>   ],
>   "playlists": [
>     {
>       "name": "All",
>       "itemIds": [
>         "archives-srfaustina1",
>         "c8168fc591444f1a8dd57f6066c26c88",
>         "01915b3a171a461ebe6e0a098d53e705",
>         "2c27a33b4eee4705971b1904490c72be",
>         "91d627fdd4dc4dc0a79737cfc5a89428",
>         "c9cdab6e098c403a86f776cf13cd68d2",
>         "55c605228e584bc6ad3788b754808943",
>         "d0f01326bd764b6991b4e8ad165f2c59",
>         "39946711a4b5461d9519797a95e09de4",
>         "4471a6ab89c444a6ac624fc6ebb69341",
>         "0236fd9efc0a4be090b1130526b86880",
>         "8cb5b158c6ae403f9ced68af25aabe73",
>         "e13adc59658e483fa519f0dca3bcd30a",
>         "b2672956cd6044158b2a9187291f6afa",
>         "3f5aab9529084f32bd02e901d9ff53b9",
>         "235b85bd90844a05865190a0fca659ff"
>       ]
>     },
>     {
>       "name": "Divine Mercy Matters",
>       "itemIds": [
>         "c8c1e4b00b144a649887cccf124522c5"
>       ]
>     },
>     {
>       "name": "Discovering the Diary",
>       "itemIds": [
>         "01915b3a171a461ebe6e0a098d53e705",
>         "4471a6ab89c444a6ac624fc6ebb69341",
>         "c8168fc591444f1a8dd57f6066c26c88"
>       ]
>     },
>     {
>       "name": "Featured Free",
>       "itemIds": [
>         "f1377ac9543c4b9795239516ef0caa64",
>         "38f3697469b4418b82fbb59945ed4aaa"
>       ]
>     },
>     {
>       "name": "Explaining the Faith",
>       "itemIds": [
>         "8cb5b158c6ae403f9ced68af25aabe73",
>         "d708716987934c26add6574788ea4117",
>         "06e25536ff004058a6453fd86ab1930e",
>         "22af8f6370434cf887072b1c7a27a4f8",
>         "39946711a4b5461d9519797a95e09de4",
>         "e13adc59658e483fa519f0dca3bcd30a",
>         "d0f01326bd764b6991b4e8ad165f2c59",
>         "2c27a33b4eee4705971b1904490c72be",
>         "1c606116194c4f73a32b5d4e6f696fb0",
>         "91d627fdd4dc4dc0a79737cfc5a89428",
>         "c9cdab6e098c403a86f776cf13cd68d2",
>         "55c605228e584bc6ad3788b754808943",
>         "0236fd9efc0a4be090b1130526b86880",
>         "b2672956cd6044158b2a9187291f6afa",
>         "3f5aab9529084f32bd02e901d9ff53b9",
>         "84633bc134db49fdbd1075d827581810",
>         "e82af69af78a464d8acf8ff0fa6ac775",
>         "a0ab3f8ce2854a7a8680ebadfd289452",
>         "f3a0024758b148a081df0e2513b270c8",
>         "3c2bf497896b4f3eab22d3bf6e239bee",
>         "b46997f173374cf2910e0a2b56d68f1c",
>         "8322cd8277164eb981f4be57f1438df0"
>       ]
>     }
>   ]
> }
> ```

That made a big difference!, now the json loads and i see most thumbnails and all descriptions, there are a few missing so that points me in the right direction

**Comment by mdenhardt** [comment]
Thank you for the help so far - if its not too much to ask, can you point me in the right direction on why 3 and a 10% of another thumbnail show, where 5 or 6 would fit across the screen? i tested on 720 and 1080 and they look about the same

**Comment by ferdiworks** [comment]
@mdenhardt Video thumbs should be Video thumbnails: 800x450 JPEG or PNG file

**Comment by ferdiworks** [comment]
@mdenhardt Y**ou wrote: why 3 and a 10% of another thumbnail show, where 5 or 6 would fit across the screen?** 

**The category row** displays whether you have 3 or more across the screen in the row!
The correct size of the thumbnails 800X450 matters for resolution and loading times and they type of image format used such as a high resolution jpeg graphic or a PNG file!

**Note if 10% show it can be an internet or wifi problem with your device or the location your video images are hosted and how fast they are accessed and the bandwidth!**

**Comment by marian-webmaster** [comment]
@ferdiworks i didnt want to hijack my own thread since the original issue is fixed, My thumbnails are most likely 1080, - i've yet to resize, but its not a bandwidth thing, it really looks like the real estate allowed for videos is smaller than the TV. When i scroll, 3 more show, and the cut off one moves left, and i see it fully
![unnamed](https://github.com/rrirower/DP2SceneGraphWizard/assets/55851201/7d25bb4b-867c-42b2-ad51-a42974105701)

**Comment by ferdiworks** [comment]
@mdenhardt If that is the TV screen you are showing, then that may be that your device needs to be 1) Updated = in settings on Device Update software.  2) Reset the settings for your TV and Screen size. 

Next, it's normal for a set of videos to show on the row and line and to have to scroll across to left or right!
The only other thing to affect the videos, are the size of videos used such as 1920 X 1080 and image size of thumbs 800 X 450
