### ISSUE TITLE
ASCII Characters

### ISSUE THREAD

**Issue by mkammes** [rrirower/DP2SceneGraphWizard#61]
**Describe the bug**
ASCII text parsed from JSON file doesn't translate into readable text.

**To Reproduce**
Channel UI shows the title and description of the media referenced in the JSON. `"&amp"` is displayed as `"&amp;"` as opposed to "&"

**Expected behavior**
The "&" symbol to be used instead of the HTML `"&amp;"`

**Screenshots**
https://photos.app.goo.gl/NjJXU61oQoWezUwE7 . It should read "Security & Access", and not "Security` &amp`; Access"

**Version number:**
1.0.0.0-alpha-9, although the manifest file says alpha-8 was used.

**Additional context**

**Comment by rrirower** [comment]
Can you provide the URL of your feed file?

**Comment by mkammes** [comment]
Sure:

https://5thingsseries.com/wp-json/tv/roku/feed.json

FWIW, this is a redirect "trick" to get a WP Smart TV feed to be generated with a .json extension - but it works.

**Comment by rrirower** [comment]
Thanks. Can you also post the manifest that it produced?

**Comment by mkammes** [comment]
```
# Channel Details
# Auto-generated by DPtoSceneGraph wizard version 1.0.0.0-alpha-8.1+657d48d4f9e549a1b4054cef74f1531ed6059d60
# (c) Copyright 2023, Michael Harnad, All rights reserved.
# Support at https://github.com/rrirower

# NOTE: Uppercase attributes are CUSTOM.

bs_libs_required=roku_ads_lib
title=5 THINGS
major_version=1
minor_version=0
build_version=2
FEED_URL=https://5thingsseries.com/wp-json/tv/roku/feed.json
splash_color=#2B2B2B
BACKGROUND_COLOR=#2B2B2B
ui_resolutions=hd,fhd
USE_RAF=0
OFFER_SUBSCRIPTIONS=0
supports_input_launch=1
mm_icon_focus_hd=pkg:/images/channel.png
splash_screen_hd=pkg:/images/splash.jpg

# Optional settings.  To use, uncomment.
#USE_THUMBNAIL_BACKGROUND=true
#TEXT_COLOR=#000000

```

**Comment by rrirower** [comment]
I initially thought this was a bug in the BrightScript code.  However, after examining your feed file, I saw that the `&amp` is actually in the text of the description.  I'm assuming that WP is encoding it that way.  I have removed the 'bug' label.

I've also corrected the version in the manifest for future releases.  Thanks for pointing that out.
