### ISSUE TITLE
"query" Content Category string does not work right

### ISSUE THREAD

**Issue by jsonnentag** [rrirower/DP2SceneGraphWizard#66]
This is in the just downloaded version.

When you have multiple "query" conditions (such as "run AND fast" the query is processed looking for everything with "run" and then everything with "fast" so you end up with duplicates of everything.  On one of my queries I had 3 terms all with AND between then and some were even common terms so even more videos were collected.

Anyway, the search and sort of "query" does not work right.  It should REQUIRE that ALL of the search terms be present in the tags of a video in order for it to be listed.  But that isn't what it does.  It basically searched for everything with term #1 and then searches everything again for term #2.

I can get around it by doing a bunch of search and replace things and just have 1 single specific identifier for each Category, but that isn't how the "query" Content Category option is supposed to work.  That isn't how it worked on the web based version of Direct Publisher's selection of Tags to require for each category.  All selected terms had an ASSUMED "AND" between them and you could string together a whole pile of them and videos collected had to have ALL of the Tags present in order to be in the Category.

Looking at the JSON feed specification I guess the AND is acting like an OR but not filtering out duplicates even if it was supposed to be doing the job of OR. (???)

[https://developer.roku.com/docs/specs/direct-publisher-feed-specs/json-dp-spec.md#category](url)

**Comment by rrirower** [comment]
I'll need to investigate this further.

**Comment by rrirower** [comment]
Can you provide a feed URL for me to test?

**Comment by ferdiworks** [comment]
@jsonnentag Did you try the Category and Playlist? Queries can return like you said indeed but playlist using video ID#s return just the category video by ID!

**Comment by jsonnentag** [comment]
> Can you provide a feed URL for me to test?

This is the one used.

[http://sabbathschooltv.com/roku/sabbathschooltv.json](url)

**Comment by jsonnentag** [comment]
> @jsonnentag Did you try the Category and Playlist? Queries can return like you said indeed but playlist using video ID#s return just the category video by ID!

No, I haven't bothered to create manual lists and don't intend to.

I can make the "query" function of Categories work by searching and replacing things and using more specific and non-overlapping Tags for things in each video rather than combinations, but just in general the actual "query" function isn't working right and needs to be fixed.

**Comment by rrirower** [comment]
@jsonnentag thanks. I think I've found the bug.  I'll test with your feed.

**Comment by rrirower** [comment]
@jsonnentag I think I've fixed the bug.  Can you provide me with the name(s) of video content you're seeing as a duplicate?

**Comment by jsonnentag** [comment]
> @jsonnentag I think I've fixed the bug. Can you provide me with the name(s) of video content you're seeing as a duplicate?

The first down the list easy to see in the 2nd Category/Row: "Reading of the Adult Bible Study Guide"

They should show from 13 on down and alternate between the reading of the lesson and the reading of some "EGW Notes".  2 different pictures (although they are all the same for each type for all 13 lessons).

It is easiest to see if you look at the Titles and Short Description (which now that it works different from in DP I'll have to make different).  :D   I never figured out for sure if adding a Long Description ever did anything for ShortForm videos.

The row with LOTS of extras is is "Hope Sabbath School" because I used 3 "query" terms with the AND and they are very common, because I didn't know what I was doing when I set things up 6 years ago and was just trying to figure things out.  :))

**There should really only be a maximum of 20 items in each Category/Row.**

Oh, that reminds me (talking about a row count), is there an easy way to modify the format of things so that it shows the item selected "out of XX" like in the original DP (and I think the main Roku Channel does the same still too)?  It's not a big deal, but some people could find it handy.

Also, is there an easy way to get both the rows/categories to loop (got from the last item to then back to showing the 1dst item) and also the actual Categories to cycle through and then get back to displaying Category #1 again?  Mostly just because that is how people are used to seeing things.  But it's not a big deal on that either.

**Comment by rrirower** [comment]
@jsonnentag I've tested your feed and it appears to load correctly.  I'll let you have the final say on that.

One thing I did notice is the use of the same thumbnail image for multiple videos.  It was confusing at first because I thought they were duplicates until I looked at the description and title.  I noticed that your feed file uses the same thumbnail image for some of the content.

The row counter will be added in the next version.  I'm going to try and get that out this weekend.

**Comment by jsonnentag** [comment]
Is there a new fixed up version to test out?

When I click on the download on the main page it still has a version from 2 weeks ago.

**Comment by rrirower** [comment]
As I stated above,

`The row counter will be added in the next version. I'm going to try and get that out this weekend.`

**Comment by jsonnentag** [comment]
> @jsonnentag I've tested your feed and it appears to load correctly. I'll let you have the final say on that.

I can't test anything until there is an updated version uploaded to use.  It still says the latest is from 2 weeks ago (well, it just changed to saying 3 weeks ago now). . . .

**Comment by rrirower** [comment]
I'm sorry for any confusion, but, an update will not be posted earlier than this weekend.

**Comment by rrirower** [comment]
Resolved in Beta1.
