### ISSUE TITLE
Channel Based on a Vimeo Feed Just shows "Please Wait. Loading" Forever

### ISSUE THREAD

**Issue by xavierpayne** [rrirower/DP2SceneGraphWizard#67]
**Describe the bug**
Thank you for this wizard. I found it to be rather straightforward.

However. When I (side) Load my channel I just get a screen that says "Please Wait. Loading" and it never seems to load.

My feed url (generated by Vimeo) is here:
https://vimeo.com/showcase/7643587/feed/roku/ebbac0334c

This is the same Feed URL I was providing to Direct Publisher.

**To Reproduce**
1. Create a Channel with the above feed URL.

**Expected behavior**
Videos are loaded and appear in the grid.

**Screenshots**

**Version number:**
 - Version [e.g. 1.0.0.0-alpha-9]

**Comment by xavierpayne** [comment]
Doing some more reading, I see this is an issue others have encountered using vimeo links:
https://github.com/rrirower/DP2SceneGraphWizard/issues/57

I don't have a way to redirect and add an extension so I modified the generated code to always assume json for my situation.

Now it loads but shows no videos. So I think the next thing I have to figure out is how to get category tags in my feed.

**Comment by rrirower** [comment]
You can try using the [Channel Feed Manager](https://github.com/rrirower/Channel-Feed-Manager) to manage and add categories to your feed file.

**Comment by ferdiworks** [comment]
I have been working with many Vimeo users who are trying to use their showcase feeds which were used with Direct Publisher! The problem was the Vimeo feeds lacked categories and or playlists! The solution was to manually add categories and/or playlists to the feeds to get the feed to work with the DP to Scenegraph software! or to get them to work with SDK Templates to create the channels. The Channel Feed Manager software is an excellent tool to have and use and once you get to understand it and how it works can be an awesome asset to the tool box!!

**Comment by rrirower** [comment]
@xavierpayne @ferdiworks Correct me if I'm wrong, but, my understanding of Vimeo is that it outputs one feed file for each showcase.  If that's the case, you can use the DP Feed Merge tool to join one or more feed files into one.

**Comment by xavierpayne** [comment]
So, I’ll need to download the Vimeo feed.

edit it and then repost it somewhere else, right?

I have a paid Wordpress account, but I think it’s not the kind that will let me host a feed.

I will try that other tool you mentioned, I appreciate all you’ve done. It might finally be time for me to retire my channel.

vimeo pro, instant tv channel, Wordpress, it’s all adding up. :-(

**Comment by ferdiworks** [comment]
@rrirower You wrote: Correct me if I'm wrong, but, my understanding of Vimeo is that it outputs one feed file for each showcase. If that's the case, you can use the DP Feed Merge tool to join one or more feed files into one.

I never used the DP Feed Merge tool and I am unaware of its use!

**Comment by rrirower** [comment]
DP Feed Merge is available in the Channel Feed Manager suite of tools.

**Comment by ferdiworks** [comment]
@xavierpayne You can use the WP Smart TV Plugin. Although it's not supported anymore it does work using a redirect plugin you can redirect the feed URL to a feed with a JSON feed URL. WP Smart TV plugin allows you to create a Roku TV Channel and host it with WP! The feed it creates is not a dot JSON so in order for the SDK Package to read the feed you need to use a URL like feed.json and use the redirect plugin!

**Comment by xavierpayne** [comment]
Ferdiworks and others, thank you very much for the help and advice. All makes sense and I hope this threads helps others.

I am going to close this out as the problem is not with the import tool.

Adding plugins to Wordpress would be another $300 a year for the lowest cost plan that allows me to add plugins.

I made the hard decision today to just shut it all down on my end.

**Comment by jsonnentag** [comment]
> Adding plugins to Wordpress would be another $300 a year for the lowest cost plan that allows me to add plugins.

I'm not exactly sure what is meant about a plan requiring extra fees for addition of plugins, but the JSON feed I use is hosted on https://x10hosting.com/ that has a $12 per year plan and it works fine for my purposes.  I have WordPress installed, but I don't know if the plugins you need cost extra for the plugins themselves or what is being referred to.  (???)

Anyway, I hate to see any loss of diversity and content on Roku, but I suspect a lot of Direct Publisher channels are going to end up the same as you described for yours. . . .

**Comment by mkammes** [comment]
WP Smart TV is not being sold any longer, although it may be heading to a public Github repo (free) in the next several weeks.

**Comment by ferdiworks** [comment]
@mkammes WP Smart TV Plugin is Free! only the addons were for sale but now they are no longer for sale and not supported anymore but does work with a redirection plugin for the feed link
