### ISSUE TITLE
Invalid File Name Automatically Created from Channel Name/Title

### ISSUE THREAD

**Issue by jsonnentag** [rrirower/DP2SceneGraphWizard#68]
I only found this out because one channel name is "What's Up Prof?" and there was an error message when it attempted to create the ZIP file.  Apparently the wizard attempts to use the exact name of the channel as the saved ZIP file name and while an apostrophe is deemed OK by Windows a question mark isn't.

I guess it could be fixed in various ways ranging from popping up a window with the default generated file name for the ZIP waiting to be OK'ed by the user (so the user has to choose where to save the file and the real final name to be used) or just check all the characters in the auto-generated file name for the ZIP and change anything not valid to an underscore or just deleted to nothing (simply delete invalid characters from the file name).

**Comment by rrirower** [comment]
Resolved in Beta1.
