### ISSUE TITLE
DP2SceneGraphWizardInstaller

### ISSUE THREAD

**Issue by fronderblash** [rrirower/DP2SceneGraphWizard#7]
hello 
Am heaving issues with DP2SceneGraphWizardInstaller, i download this tool but i can't  install it, this what am facing
![uhny3h4f](https://github.com/rrirower/DP2SceneGraphWizard/assets/141512200/a445bac8-6b66-4300-9728-257cfd268dec)

 please can someone help me?

**Comment by ferdiworks** [comment]
Are you installing the Alpha 3 version?

Did you download the EXE file?
https://github.com/rrirower/DP2SceneGraphWizard/releases/download/1.0.0.0-alpha-3/DP2SceneGraphWizardInstaller.exe

Your system must meet the following minimum requirements to use the DP2SceneGraph Wizard tool.

64-bit Windows 10 or higher.
.Net 7 framework.
30 MB Hard disk space.

**Comment by rrirower** [comment]
Please make sure your computer meets the requirements posted for the software. You may need to install .Net 7 manually.

**Comment by caloriesm** [comment]
hello

i try to open subscription and Ads setup on DP2SceneGraphWizardInstaller but it don't open, what happened 
![ssdfddf](https://github.com/rrirower/DP2SceneGraphWizard/assets/141550793/45eacdf8-2a46-4b77-a4ad-bf026d61a3a6)

**Comment by rrirower** [comment]
From the release notes for the wizard:

"Add future support for RAF and Subscriptions (not implemented - future release)."

Those features are not implemented yet. They will be in a future release.

**Comment by fronderblash** [comment]
ok thanks

**Comment by fronderblash** [comment]
https://github.com/rrirower/DP2SceneGraphWizard/assets/141512200/16c7d8b4-0f2e-4da7-af38-07c9b0379af0

can this be splash screen on Roku sdk package??

**Comment by rrirower** [comment]
This version of the code that is produced by the wizard does not play MP4 files as a splash screen. I'm not sure if you can since the manifest requires an image file. Perhaps with some custom coding of your own you can accomplish that .
