### ISSUE TITLE
Channel Images - Warning, but who knows what they want at any given time

### ISSUE THREAD

**Issue by jsonnentag** [rrirower/DP2SceneGraphWizard#70]
I just packaged and submitted a channel and one of the non-critical/blocking warnings was about image size for "channel.jpg"

I used the size listed on this page and there is nothing on the page that matches the size they claim to want.  :))

https://developer.roku.com/docs/specs/graphics.md

Every place you look seems to have a different set of dimensions for things.  This is the "warning" message (apparently warnings don't kill channel publication but might at some future point in time).

"/images/channel.jpg" image used for "mm_icon_focus_hd" attribute has
invalid resolution: "540x405". Valid resolution is "290x218". Path: /manifest.
Line: 20.
Warning Manifest

I think the images are sized to fit if they don't match what they say they want.  They should just decide on a "high enough" resolution and aspect ratio and then upload 1 channel image and forget it!  3 images total - 1 for channel, 1 for background, and 1 for "overhang" and call it good enough.  :)

I'll attach a PDF of the warnings page for info.  The only think I changed in the ZIP'ed files spit out by the wizard was the channel name in the manifest so that it has a "?" on the end, since you can't put that in and have the wizard write a file correctly.

[Static Check Warnings.pdf](https://github.com/rrirower/DP2SceneGraphWizard/files/13790226/Static.Check.Warnings.pdf)

**Comment by rrirower** [comment]
Are you reporting a problem with the software?  Should this be posted as a "discussion" instead?

**Comment by jsonnentag** [comment]
I would say the only "problem" in the wizard might be the unclear specification of what the various images really are called.  It would be better if the specific and exact name/labels used by Roku (along with the dimensions - if you can find their real latest approved and official ones . . .) along with the dimensions to use for each were specified in the wizard.

The link in the wizard goes to a place that uses different names for things than what is in the wizard.  100% exact correlation always makes things perfectly clear.  :)

**Comment by jsonnentag** [comment]
Oh, and also for all the other warnings that Roku spits out during the static testing it would be nice if the option in the wizard to NOT include using the payment or registration and everything else they put a warning for could remove the "offending" code from the ZIP so that the errors/warnings aren't created.

I saw in one comment some item/variable started with "bs" something or other required by Roku.  :))

**Comment by rrirower** [comment]
Resolved in Beta1.
