### ISSUE TITLE
Highlighted Video No Description Info + Click 2 times to start playing

### ISSUE THREAD

**Issue by jsonnentag** [rrirower/DP2SceneGraphWizard#71]
I tested out the latest (beta1) and was liking the labeling of what video is highlighted (XX of XX) but then I noticed that the descriptions that used to be at the top of the screen that change as the selected episode changes are not there anymore!

Then I pressed the OK button and it went to a page that ha a button icon for Play and you have to press OK again to get the video to play.  Not in a Series, just a single shortform type.  So rather than click 1 time to start the video playing you have to press OK 2 times and then you have no idea (except for thumbnail image) what you are playing.

I think this version needs to be pulled and deleted.  :)

**Comment by jsonnentag** [comment]
Even worse, as I somewhat suspected it doesn't matter if the wizard is switched back to the previous version because the files used are downloaded EVERY SINGLE TIME and a basic setup of files isn't stored locally.

Well, I guess I can just modify the other channel already submitted to Roku to have these SSTV files.  Basically just the splash, overhang, and background images change along with the channel name in the manifest.

Anyway, I think "beta1" is far worse than the last alpha.  (I modified tags in the SSTV feed so that it didn't matter anymore if the "query" worked right or not.)

**Comment by rrirower** [comment]
Can you post an image that shows your complaint?

**Comment by jsonnentag** [comment]
Well, that looks completely different from what I see.  I got the latest version after the e-mail came out 94 hours after I think it said) and I just ran the wizard again with the same results.  It is the wizard you added the listing of expected dimensions of 2 of the JPGs for and I guess the files it just downloaded at wizard startup are the latest.  (???)

Here is what I see:
(Main Screen - No Title or Short Description)
![Main_Screen](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/30eb6406-27e7-41f7-bcf8-9a0a75fb6610)

(Video Selected to Play - Nothing but a Play Button - ???)
![Video_Selected_to_Play_Screen](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/43ca55f2-74a2-4160-a684-03330aa134ac)

**Comment by jsonnentag** [comment]
I guess 1 difference I see in the setup you created is that there is no overhang and I always use the Overhang option for the top left corner.  (???)

**Comment by rrirower** [comment]
I don't see overhang being used that much in too many channels. It probably interferes with the code. I'll have to take a closer look at that.

**Comment by jsonnentag** [comment]
Well, it isn't caused by an Overhang JPG being used.  So it is something else the REALLY needs to get fixed.

I removed both the Overhang and Background JPGs during the wizard run just now and no video Title or Short Description is being shown.  (???)   So I don't know what is different in the one you managed to create from the feed.  Something is matching between your results and my results.  (???)

![HD_Scaling_But_No_Descriptions](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/cfe68f6e-346f-4bf3-8638-43e54ac61153)

**Comment by rrirower** [comment]
Did you change any color settings for text?

**Comment by jsonnentag** [comment]
No, no color changes other than Background and Splash.  Manifest is pasted below.

(I just found out that you can't select a file to attach by browsing if it has no file extension.  Thus the copy and paste of the manifest file.)

![image](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/88c5ec31-5872-42c9-bdb5-9732f6065cc8)

# Channel Details
# Auto-generated by DPtoSceneGraph wizard version 1.0.0.0-alpha-8.1+657d48d4f9e549a1b4054cef74f1531ed6059d60
# (c) Copyright 2023, Michael Harnad, All rights reserved.
# Support at https://github.com/rrirower

# NOTE: Uppercase attributes are CUSTOM.

bs_libs_required=roku_ads_lib
title=Sabbath School TV
major_version=60
minor_version=1
build_version=0
FEED_URL=http://sabbathschooltv.com/roku/sabbathschooltv.json
splash_color=#000000
BACKGROUND_COLOR=#000000
ui_resolutions=hd
USE_RAF=0
OFFER_SUBSCRIPTIONS=0
supports_input_launch=1
mm_icon_focus_hd=pkg:/images/channel.jpg
splash_screen_hd=pkg:/images/splash.jpg
OVERHANG=pkg:/images/overhang.jpg
BACKGROUND_IMAGE=pkg:/images/background.jpg

# Optional settings.  To use, uncomment.
#USE_THUMBNAIL_BACKGROUND=true
#TEXT_COLOR=#000000

**Comment by jsonnentag** [comment]
Well, I just noticed that paste was from the one I am using that has the Background and Overhang JPGs.  Also noticing that the "#" at the beginning of some like makes the text Title sized or something.  (???)

Here's the manifest created in the test of the latest with no Background or Overhang.  I added a .txt to the manifest to see how it pastes from a file attachment this time.

[manifest.txt](https://github.com/rrirower/DP2SceneGraphWizard/files/13814544/manifest.txt)

**Comment by jsonnentag** [comment]
Also, if there really was something being printed on the screen that was just hidden due to text color the Play Button wouldn't be stuck at the top of the screen the way that it is (on the ones created here vs. down under the video info text on the one you managed to create).

**Comment by jsonnentag** [comment]
Just for fun I re-did the whole wizard loading nothing from the past to start with and adding only the bare minimum of Channel Name, Feed File, Splash JPG, and Channel JPG.  Not changing of background colors or anything else.  Pasted below are the results of that channel loaded with views of the main screen and then a view of the play screen that appears when you select a video to play.  The manifest with .txt added to the end is attached too.

[manifest.txt](https://github.com/rrirower/DP2SceneGraphWizard/files/13814632/manifest.txt)

![Main_Screen](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/c52d3114-c376-456f-8cfd-70450acddef3)
![Play_Screen](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/bff3cb0d-c9ef-45b1-a9a7-c249b0e8de28)

**Comment by jsonnentag** [comment]
Just to be REALLY sure I had the latest of everything and entering the bare minimum I just uninstalled the wizard (since when I installed the latest one and then re-installed the previous version and then re-installed the latest again the first time I never uninstalled anything between).  After uninstalling I rebooted and downloaded the wizard from GitHub again (just to be sure). . . .

Absolutely no difference.  I entered the bare minimum 4 items listed above and got exactly the same results.

**Comment by ferdiworks** [comment]
@jsonnentag I think I found your issues, Thery are fixed with version 3 see attached
[source.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/13815030/source.zip)

**Comment by rrirower** [comment]
@jsonnentag have you made any source code changes?  Is your Roku OS at 10.5 or higher?

**Comment by rrirower** [comment]
@jsonnentag also, please upload your package zip file that shows the issue so I can test on my end.

**Comment by jsonnentag** [comment]
> @jsonnentag I think I found your issues, Thery are fixed with version Alpha 3 - see attached [source.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/13815030/source.zip)

**(???)  Fixed in Alpha 3?!  The version linked to for downloading right now is Beta 1.  (???)**


> @jsonnentag have you made any source code changes? Is your Roku OS at 10.5 or higher?

**No, all I have ever done is download the EXE file for Windows installation.**


> @jsonnentag also, please upload your package zip file that shows the issue so I can test on my end.

**ZIP file for the last attempt with bare minimum 4 input wizard run using installation EXE that was just DL'ed yesterday after uninstalling what was installed previously and restarting the computer is attached.**

[SSTV.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/13821168/SSTV.zip)

**Comment by ferdiworks** [comment]
@jsonnentag I am asking you to sideload the older version alpha 3 to see if the layout and details page show and display is what you are looking for! For some reason the layout changed in future enhancements and I personally liked the layout from Alpha 3

**Comment by jsonnentag** [comment]
> > @jsonnentag I think I found your issues, Thery are fixed with version Alpha 3 - see attached [source.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/13815030/source.zip)
> 
> **(???) Fixed in Alpha 3?! The version linked to for downloading right now is Beta 1. (???)**

Also, it doesn't matter what wizard version is running.  The newly downloaded set of files the wizard puts into a folder/directory each time is the problem.  I ran the latest version when you first said it was ready (Beta 1) and saw the files downloaded by that include extra JPGs.  The problem of no video titles and descriptions appeared so the previous Alpha version was installed and that Alpha version ALSO downloaded the same set of apparently "latest" files (and all you can get) version of the working files that included all the extra JPGs in the "images" directory.  So due to that lack of option for what files are downloaded at the beginning of a wizard run use of the wizard at the moment is useless.  In order to have things to send to Roku I had to modify the manifest for an old version created BEFORE you sent out and setup the Beta 1 version of things the messed things up.

**Comment by jsonnentag** [comment]
> @jsonnentag I am asking you to sideload the older version alpha 3 to see if the layout and details page show and display is what you are looking for! For some reason the layout changed in future enhancements and I personally liked the layout from Alpha 3. Note you can unzip and edit the images and manifest file AND REZIP IT. Alpha 3 did not support mrss feed and did not support subscriptions or ads but the layout I thought was good!

Yes, the previous Alpha 3 version works fine.  That i the version I had to modify for the 4 channels uploaded to Roku.

**Comment by ferdiworks** [comment]
@rrirower I think it would be something to look back on = The layout from ALPHA 3 and the layout in The newest version are a total different look on the details screen. The newest version has a play button, no graphic and the text sometimes is under the play button. I personally would like to see the look of the details page or play page whatever you call it now be like it was in the Alpha 3

**Comment by ferdiworks** [comment]
@jsonnentag You don't need the wizard tool to use Alpha 3 or any other versions. All you need is the zip file and you can manually edit the zip file, manifest file, and change the images!

**Comment by jsonnentag** [comment]
I'm fine with the Alpha 3 version that just has better working "query" action for Categories.  :)

Although, the indicator on the right side showing the selected video number out of the total in the Category was a nice improvement.  I didn't particularly like the extra play button or find the larger image of the video selected shown on the top right very useful.  I'd prefer more room for the video/episode description to appear in.

**Comment by ferdiworks** [comment]
@jsonnentag and anyone else reading this!If you created a channel with the wizard from any version that you liked please save a backup copy of the output zip file. Save it as a template! Unzip the folder and use a text editor like notepadd++ on windows or another for Mac and edit the images, edit the manifest file rezip, and sideload and test!

**Comment by ferdiworks** [comment]
@jsonnentag We may be able to go in the source file for the current version and try to enhance the details page and the video counter you mentioned and see if we edit the bright script code we can make our own enhancement!

**Comment by rrirower** [comment]
@jsonnentag @ferdiworks I'm not sure why you won't let me try to resolve this.  I would appreciate it if you continue this offline if you want to continue working together.

**Comment by jsonnentag** [comment]
> The new version of the software uses a field object that was introduced in Roku OS 10.5. Have you verified that your Roku is at that version or higher.

I have 12.5.5 build 4174-04 installed

I'm going to put the same ZIP I attached onto this TCL 4K TV that I use as a computer monitor that IS NOT on the Roku beta testing (so it has 12.5.0 build 4176-CG) and paste on here what the screen looks like. . . .

**Comment by jsonnentag** [comment]
So this is the result. . . .

Apparently Roku beta versions aren't using that field object that you said was introduced into 10.5, because on the non-beta TV I tested (12.5.0) it does in fact show up as you pasted above.

So I'm still going to stick with the Alpha 3 version of things and won't be surprised if things don't look right for everybody using the latest wizard and files for channel construction in the next Roku update that everybody gets.

**Comment by jsonnentag** [comment]
> @jsonnentag @ferdiworks I'm not sure why you won't let me try to resolve this. I would appreciate it if you continue this offline if you want to continue working together.

:))  I wasn't even paying attention to who was replying and thought I was talking to the creator of the wizard.  :))

**Comment by rrirower** [comment]
@jsonnentag Can you explain what you mean by "Roku beta versions"?  The Roku OS is firmware that is loaded onto the device.  Are you part of a Roku Beta Test system?

**Comment by jsonnentag** [comment]
> @jsonnentag Can you explain what you mean by "Roku beta versions"? The Roku OS is firmware that is loaded onto the device. Are you part of a Roku Beta Test system?

Yes, I have multiple devices enrolled in the beta testing: Roku 3, Roku 4, either 1 or 2 TVs (but the TVs don't usually get anything sent to them ever or maybe just right before a new version goes out to everybody).

**Comment by rrirower** [comment]
Thanks for the clarification.

**Comment by jsonnentag** [comment]
Well, this is even MORE strange!

I decided to test out the ZIP on the Roku 4 with the latest beta OS from Roku (the most recent 12.5.5 build) and when I copied it over using web browser method it looked the way it is supposed to with the Titles and Short Descriptions visible!

So I decided to try exactly the same thing on the Roku 3 and it shows things right even on the Roku 3 if you side load through a browser.  So THAT was pretty strange!  The only thing different all the times before is that I used Visual Studio Code all the times before to modify the manifest and copy things over to the Roku devices.

So I decided to replicate that and if you copy things over with Visual Studio Code and the BrightScript Debug addon it doesn't work right.  It messes up the display of the Titles and Short Descriptions.

There must be something in the BrightScript addon that does something to the code before it compresses and sends it off to the device.

**So that is something to tell people about so they don't have the same problem!**

**Comment by rrirower** [comment]
@jsonnentag I'm not sure what your process consists of, but, I've been using VSCode for BrightScript for a while and I don't have any problems loading a channel after making code changes.  There may be something else going on in your system.

**Comment by jsonnentag** [comment]
Do you actually transfer the files using the "Run and Debug" button that creates and uses a file called "launch.json" and contains the IP address and password?  Or do you just modify things and then go to the directory of source files and ZIP and then transfer through a browser connection to the IP address of the Roku device?

Because I just tested out ZIP'ing the extracted files manually and NOT using the "Run and Debug" button option and it copied over a working copy.  But re-doing the same thing using the same directory of files and having VSCode transfer things with the "Run and Debug" process led to the same non-functional version being installed again that doesn't have the Titles and Sort Descriptions displayed anywhere.

![image](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/a6497f11-477d-4a9b-9352-0a0096c29719)

**Comment by rrirower** [comment]
Yes, I run the debugger which uses the launch file.  But, there's one difference.  I also use BrighterScirpt which introduces a "bsconfig.json" file that creates a zip file and loads it on my device.

**Comment by ferdiworks** [comment]
@jsonnentag I too have been a developer for many years and still do develop! However, what @rrirower has done with the software has been a time saver with many small or many channels that don't need anything special. The software is great and has been proven to work on over thirty something channels! tHE ONLY TIME I MESS WITH THE CODE IS IF I WANT TO ADD AN ENHANCEMENT!

**Comment by rrirower** [comment]
Please see beta2 release for updates that should help.
