### ISSUE TITLE
TEXT_COLOR=#... doesn't change the color of the recently added Title and Short Description

### ISSUE THREAD

**Issue by jsonnentag** [rrirower/DP2SceneGraphWizard#73]
The option in the Manifest file for TEXT_COLOR doesn't change the color of the text for the recently added Title and Short Description in the channel.  The text for the Category Name and selected video number (X of XX) changes with the variable setting, but the color of the video Title and Short Description remains the same blue color.

Where would I go in the code files to change that text color?

**Comment by jsonnentag** [comment]
I think I searched out and found the special fonts descriptions (font, size, and color) in "fontsupport.brs" in the Source subdirectory.  That would be good to tell people so they know where to look for things and can define their own colors and sizes.

But the Play, Play All (I capitalized and A on All), Resume, Restart, and Episodes text visible when not highlighted was still dark blue.  So it would be good to tell people they can modify that down in the LayoutGroup part of DetailsScreen.xml in the DetailsScreen subdirectory in the Components subdirectory **if the text selection color isn't going to modify those things automatically**.

**Comment by rrirower** [comment]
This project, like most on GitHub, provides a [Wiki](https://github.com/rrirower/DP2SceneGraphWizard/wiki) for documentation.  The info for using the wizard and its code can be found there.  The project itself, as stated, was meant to be a starting point for channel developers to convert their Direct Publisher channels to SceneGraph.  Unfortunately, I don't have the time to document all of the complexities of the code.  I would expect users to explore the code, as you did, to find and modify it to meet their needs.

When appropriate, I will document changes in more detail.

**Comment by jsonnentag** [comment]
So is it possible for anybody other than you to modify or add to the wiki, this page in particular?  I think more specifics would be helpful for people, especially for the Play, Play All, . . . font color that doesn't change with the changes in the fonts brs file.

[https://github.com/rrirower/DP2SceneGraphWizard/wiki/How-to:-Change-the-text-color-scheme](url)

Also, how about helping people out who are new to the whole wizard by adding a link to the wiki page on this main page (down in the Support section I would image as the most appropriate):

[https://github.com/rrirower/DP2SceneGraphWizard](url)

**Comment by rrirower** [comment]
No, it is not possible for others to modify the wiki.  I believe there is a link at the top of the project page for the wiki.

**Comment by aaronmspelling** [comment]
What version should I download if ii wanted to use the old version where we had a channel log and the video page video thumbnail - Until this version is more evolved...

I don't mind; we don't have a channel logo, but I tried for hours to change that blue color, and I can't -  and the video page is just too.... empty 
the older version if perfect for my needs right now.
thanks

**Comment by rrirower** [comment]
@aaronmspelling I will be releasing a newer version soon. In the meantime, take a look at the wiki. It explains how to change the text attributes and some other custom settings to affect the look of the UI.  Bear in mind, some attributes are not implemented yet and will come in the next version.

**Comment by ferdiworks** [comment]
@aaronmspelling _ edited version 1.0.0.0-beta1 with an Alpha3 version type look, Here is the file to edit the manifest!
[source.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/13911199/source.zip)

**Comment by rrirower** [comment]
Please see Beta2 release for updates that should help.

**Comment by ferdiworks** [comment]
@rrirower You done a great job here and made it easy to change the color codes from the Fontsupport.brs file. Awesome work!

**Comment by rrirower** [comment]
Thanks.
