### ISSUE TITLE
Roku sdk requires deep linkling?

### ISSUE THREAD

**Issue by furynightwing** [rrirower/DP2SceneGraphWizard#75]
what do i put in the deep linking section? does this even support deep linking?
![Capture](https://github.com/rrirower/DP2SceneGraphWizard/assets/156032328/9d89989d-d82c-4c20-97e8-40f9b29b759d)

**Comment by furynightwing** [comment]
Also, how do i downsize? apparently roku does not support channels that are over 4 megabytes, however i dint add anything, just used the generator
![Capture](https://github.com/rrirower/DP2SceneGraphWizard/assets/156032328/38ab141b-f759-4e5c-b477-3c666d2f628a)

**Comment by ferdiworks** [comment]
@furynightwing On the left select type of video from your feed, exam,ple = short-form video or Movie, Etc! On the right go into your feed, and get the video ID number, and enter it! Next place a short description under that! = Save and done with deep linking!

**Comment by furynightwing** [comment]
am i supposed to do that with all of my videos?

**Comment by furynightwing** [comment]
why just one tho?

**Comment by ferdiworks** [comment]
@furynightwing Thats what Roku ask of you because of the deep linking in SDK package they only want one to see your link

**Comment by furynightwing** [comment]
ohh! ok
thanks

**Comment by ferdiworks** [comment]
@furynightwing You will see once you add one link you will get a check mark for publishing

**Comment by furynightwing** [comment]
yes i did! so quick question tho, so now will it add all the videos in my feed for deeplinking too, or just that one?

**Comment by ferdiworks** [comment]
@furynightwing Your feed will add all the videos
