### ISSUE TITLE
Wizard labels Overhang as Splash Image in final review

### ISSUE THREAD

**Issue by jsonnentag** [rrirower/DP2SceneGraphWizard#78]
I just noticed this when I was going to compare the setup view of things with and without an Overhang image.  On the final review screen of the wizard it has Splash image listed 2 times and the 2nd one is supposed to be the Overhang image.

![image](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/a1141310-5927-4655-afb5-2e3c9a154325)

**Comment by rrirower** [comment]
Fixed in beta3.
