### ISSUE TITLE
Sideload stuck at "Please wait.  Loading channel feed.."

### ISSUE THREAD

**Issue by DoubleACS** [rrirower/DP2SceneGraphWizard#81]
I was able to follow the wizard and create the zip file.

When I sideload the .zip file the icon, splash screen, and background show.  But all I see in the middle of the screen is "Please wait.  Loading channel feed."

As an aside, the feed does pass the "Channel Feed Manager" import.

My feed is hosted on npoint.io
The feed is: https://api.npoint.io/037597a6caef28cb8765

In the manifest file I add .json to the feed (https://api.npoint.io/037597a6caef28cb8765.json) .  This link brings up the feed.

There are about 350 items in the feed.  This is the exact feed the Direct Publisher used.

If you need any other information please let me know.  

I am not sure what I am doing wrong.  Thank you.

**Comment by rrirower** [comment]
Please indicate the version you are using. It can be found in main.brs in the source folder.

**Comment by DoubleACS** [comment]
1.0.0.0-beta2

I downloaded the installer yesterday.

**Comment by rrirower** [comment]
On inspection of your feed file, you have several 'rating' syntax errors.  Your feed file defines the 'rating' object as:

`"rating": "PG",`

but, the [rating field is actually an object](https://developer.roku.com/docs/specs/direct-publisher-feed-specs/json-dp-spec.md#rating) that needs to be defined like:

```
"rating": 
{ 
  {
    "rating": "PG",
    "ratingSource": "USA_PR"
  }
}
```

The Channel Feed Manager did flag those errors.  However, a bug, prevented it from displaying them to you.  That bug will be fixed.

**Comment by DoubleACS** [comment]
Thank you.  That solved it.
