### ISSUE TITLE
Only the first series in each category is playing.

### ISSUE THREAD

**Issue by sajidbux** [rrirower/DP2SceneGraphWizard#82]
**Describe the bug**
Only the first series in each category is playing. Suppose we go to category Action and click on the first series shown then all episodes play. But whenever we go the any other series apart from the first the channel crashes. This is happening for series with multiple episodes. Single videos are not displaying the problem and are working fineI have been able to get the error log which I am attaching. 
**To Reproduce**
1. Go to 'Any category'
2. Click on 'Any series apart from the first one listed'
3. Scroll down to 'Any episode in the screen'
Channel crashes

**Expected behavior**
We should play any episode from any series regardless of position in each category
[Doc1.docx] (https://github.com/rrirower/DP2SceneGraphWizard/files/14024096/Doc1.docx)

**Screenshots**

**Version number:**
 - Version [e.g. 1.0.0.0-alpha-8]

**Additional context**

**Comment by rrirower** [comment]
Alpha-8 is an old version. Please update to the latest (beta2) and retry.

**Comment by sajidbux** [comment]
Hi Used the latest version. Having the same issue.

**Comment by rrirower** [comment]
Can you provide the feed URL you are using?  I've got two series within the same category and both play without any errors.

**Comment by rrirower** [comment]
Have you resolved this?

**Comment by sajidbux** [comment]
No not yet. But have tries some trouble shooting. I believe the code needs to be modified to adjust to the format of my feed because when i tested my feed with the sample channel codes given by Roku the problem is not occurring.  My feed has been directly take as per the json Roku Direct Publisher feed format generated in WP Smart TV. I am attaching sample snippet of my feed format. Some information has been dashed out. The videos should be laid out as per categories mentioned in the last part of the feed
[Json Feed.txt](https://github.com/rrirower/DP2SceneGraphWizard/files/14066491/Json.Feed.txt)

**Comment by rrirower** [comment]
If you want me to resolve this for you, I'll need the URL for your feed file so I can debug the code.

**Comment by rrirower** [comment]
I tried loading the file you posted as a feed file into the Channel Feed Manager. It failed to load with the following problems.

```
{ "time": "2024-01-26 14:48:38.3228", "level": "ERROR", "message": "Error converting value \"tvSpecials\" to type 'JsonManager.SeriesObject'. Path 'series[1]', line 116, position 12." }
{ "time": "2024-01-26 14:48:38.3228", "level": "ERROR", "message": "After parsing a value an unexpected character was encountered: :. Path 'series[1]', line 116, position 12." }
{ "time": "2024-01-26 14:48:38.3228", "level": "ERROR", "message": "Infinite loop detected from error handling. Path 'series[1]', line 116, position 12." }
{ "time": "2024-01-26 14:48:38.3228", "level": "ERROR", "message": "After parsing a value an unexpected character was encountered: :. Path 'series[1]', line 116, position 12." }
{ "time": "2024-01-26 14:48:38.3337", "level": "FATAL", "message": "Program exception detected: 'Object reference not set to an instance of an object.' in method 'CreateChannelObjectFromFeedFile'." }
{ "time": "2024-01-26 14:48:38.3337", "level": "FATAL", "message": "Error converting value \"tvSpecials\" to type 'JsonManager.SeriesObject'. Path 'series[1]', line 116, position 12." }
{ "time": "2024-01-26 14:48:38.3337", "level": "FATAL", "message": "After parsing a value an unexpected character was encountered: :. Path 'series[1]', line 116, position 12." }
{ "time": "2024-01-26 14:48:38.3337", "level": "FATAL", "message": "Infinite loop detected from error handling. Path 'series[1]', line 116, position 12." }
{ "time": "2024-01-26 14:48:38.3337", "level": "FATAL", "message": "After parsing a value an unexpected character was encountered: :. Path 'series[1]', line 116, position 12." }
{ "time": "2024-01-26 14:48:38.3337", "level": "FATAL", "message": "The feed file, 'C:\\Users\\Mike\\Documents\\Channel Feed Manager\\Channels\\Channel feeds\\Sajidbux.json', could not be added to your library because it contains errors.  Please view the log file for more info." }
```
I think you may have a misplaced bracket, comma, or some other syntax error.

**Comment by rrirower** [comment]
The syntax error is obvious if you load the file into Notepad+ and collapse the 'Series' line.  The tvSpecials object appears to be within the Series object.

**Comment by sajidbux** [comment]
Hi finally found the issue. In SeasonsWithEpisodesScreenLogic.brs in UILogic folder under components, the last line of code calling HandlePlayButton function is given the inputs (m.content,0). It should be HandlePlayButton(m.content,m.selectedIndex[1]). 
Thanks for the wonderful app which really helped convert my Direct Publisher channel to SDK.

**Comment by sajidbux** [comment]
I have currently published without monetization. Might need your help whenever i monetize to ads or subscription and face any issues.

**Comment by rrirower** [comment]
You'll need to open a discussion if you need help.
