### ISSUE TITLE
The brightscript template does not show series/seasons/episodes if present in the JSON feed

### ISSUE THREAD

**Issue by eNEtv** [rrirower/DP2SceneGraphWizard#83]
The generated brightscript package does not parse / display the series / seasons / episodes on the main screen.

I have used your DP2SceneGraphWizard with an existing JSON which works on Roku Direct Published "Hero Row" template just fine.
I am attaching below the feed URL https://s3.amazonaws.com/ene.tv.useast1/feed.json

1. Run the DP2SceneGraphWizard wizard
2. When prompted provide this feed URL https://s3.amazonaws.com/ene.tv.useast1/feed.json
3. Complete the wizard and locate the zip package
4. Deploy the zip package to the Roku device
5. Launch the app on Roku and note that series / seasons / episodes are missing

Please let me know if you need any additional information besides the reproducing steps above.
Many thanks for your hard work on the DP2SceneGraphWizard tool.

**Comment by rrirower** [comment]
What version are you using?  Take a look in main.brs at the top.

**Comment by rrirower** [comment]
I can confirm, it's a bug.  I should have it fixed soon.

**Comment by eNEtv** [comment]
On the main.brs the version at the top shows 
BrightScript code version 1.0.0.0-beta2

**Comment by rrirower** [comment]
Beta3 was released yesterday.  Consider adding yourself as a 'watcher' or starring this project so you can receive notifications of new versions.

Also, please consider adding your experiences with this project to the [Success Stories](https://github.com/rrirower/DP2SceneGraphWizard/discussions/55) discussion.

**Comment by rrirower** [comment]
I should have a fix sometime tomorrow.

**Comment by rrirower** [comment]
Fixed in Beta.3.1.
