### ISSUE TITLE
Button Color

### ISSUE THREAD

**Issue by aaronmspelling** [rrirower/DP2SceneGraphWizard#84]
hi
i tried to change the color of the text inactive buttons like play, resume, episodes, and so on, from the video page - or series/episodes.
can you guide me in the right direction if it is possible of course?
![iindiiv page](https://github.com/rrirower/DP2SceneGraphWizard/assets/69145314/871bc7ad-93cc-4aec-ab3b-c28767e4d692)

thanks

**Comment by rrirower** [comment]
The 'ButtonGroup' in _DetailsScreen.xml_ controls those attributes.
