### ISSUE TITLE
"Play All" button brings up black screen only

### ISSUE THREAD

**Issue by JLNjolo** [rrirower/DP2SceneGraphWizard#85]
I met the Jan 12 deadline to update my 2 Channels, using your (then) updated software on a Windows 10 PC.  I just noticed on my Channels the "Play All" button doesn't work, but it brings up a black screen showing only the date at the top-right of the screen.  Is there an update on this? Thanks, John

**Comment by rrirower** [comment]
What version are you using?  Look in the main.brs file at the top.

**Comment by JLNjolo** [comment]
Nothing anywhere in main.brs on the version. The latest software was downloaded and installed December 15th.

**Comment by rrirower** [comment]
You have to edit the main.brs file.  The version number is a comment at the top of the file.

If you downloaded and installed it on our about December, you're using an old version.  I suggest you download the latest beta version and try it.

Also, if you haven't already, you should set yourself up as a "watcher" of this project or "star" it to be notified when new versions are released.

**Comment by rrirower** [comment]
Do you have an update on this?

**Comment by JLNjolo** [comment]
The "Play All" button is working now. The layout is better but the text is a dark blue on my black background.

How do I change it to white?
________________________________

**Comment by rrirower** [comment]
Please refer to the project wiki for info on how to change colors and fonts.

**Comment by JLNjolo** [comment]
OK. Thank you.

**Comment by JLNjolo** [comment]
I also noticed the title isn't there, and the logo image is smaller. But the overall look is much better. Good work!

**Comment by JLNjolo** [comment]
It's too complicated for me.
________________________________
