### ISSUE TITLE
Series Thumbnail Issue

### ISSUE THREAD

**Issue by JLNjolo** [rrirower/DP2SceneGraphWizard#95]
Channel Feed Manager:

Category:

Episodes:

Episode thumbnails do not change with each episode highlighted, only the thumbnail from episode one. 

Also, it would be nice if only the category thumbnail showed on the episode screen, since each episode has it's own thumbnail, which would remind the viewer of what category they are actually viewing.
![20240310_102208](https://github.com/rrirower/Channel-Feed-Manager/assets/55280239/0fcc917d-b423-4b50-9b91-93fb0ca02851)
![20240310_102222](https://github.com/rrirower/Channel-Feed-Manager/assets/55280239/06ea8fdc-94ef-401e-8e0d-6560c6069128)
![20240310_102229](https://github.com/rrirower/Channel-Feed-Manager/assets/55280239/f40b2473-057c-498c-ab01-db1c4bc95c65)
![20240310_102339](https://github.com/rrirower/Channel-Feed-Manager/assets/55280239/cea73914-2938-4a69-8392-ea4bedd15c15)
![20240310_102443](https://github.com/rrirower/Channel-Feed-Manager/assets/55280239/dd6fcd2d-b34c-45ec-a4fa-020bd1654eff)

**Comment by rrirower** [comment]
This works as designed.  The image on the top left is the thumbnail of the Series, not, every Episode.

**Comment by JLNjolo** [comment]
This is that series thumbnail listed in "Series Attributes for Series with Episodes ony"
https://jesuslivenetwork.com/roku2018/images/kenandersonfilms.jpg
The one showing on each episode at the left is the thumbnail from the first episode.

**Comment by rrirower** [comment]
Please post your feed url so I can test it.

**Comment by JLNjolo** [comment]
https://api.jsonserve.com/XIli8a

**Comment by rrirower** [comment]
Thanks for posting your feed URL.  With it, I was able to validate that this is a bug.  It will be fixed soon.

**Comment by JLNjolo** [comment]
OK. Thank you!!

**Comment by rrirower** [comment]
Resolved in beta.5 release.

**Comment by JLNjolo** [comment]
I see Version 1.0.1.2 as the latest release Feb 12 for the installer.
________________________________

**Comment by rrirower** [comment]
That's the installer for the Channel Feed Manager, not the wizard tool.

**Comment by JLNjolo** [comment]
OK, sorry.
________________________________

**Comment by rrirower** [comment]
If you're seeing those items on the screen, that means that the manifest has them enabled (ie. they are NOT commented out with a leading '#' in the manifest file).  If you don't want them, add a '#' in front of them in the manifest file.  A '#' means this line is a comment and is ignored.

Removing the '#' and setting the value to false will accomplish the same thing.

**Comment by JLNjolo** [comment]
Thank you. The Channel looks awesome. I've added scores of Series and videos using your software.
________________________________

**Comment by rrirower** [comment]
I'd love to see your channel.  Has it been published?  If so, what's it name so I can take a look?

Please consider adding your experiences to the '[Success Stories](https://github.com/rrirower/DP2SceneGraphWizard/discussions/55)' discussion.

**Comment by JLNjolo** [comment]
Sure. And I'll be glad to add my experience to  your "Success Stories" discussion.

https://channelstore.roku.com/details/20411/jesus-live-network
[https://www.roku.com/assets/roku-logo-purple.png]<https://channelstore.roku.com/details/20411/jesus-live-network>
Roku<https://channelstore.roku.com/details/20411/jesus-live-network>
Roku provides the simplest way to stream entertainment to your TV. On your terms. With thousands of available channels to choose from.
channelstore.roku.com

________________________________

**Comment by JLNjolo** [comment]
Hi,
I just got this from Roku. Do you have a software solution or update that
would make this easier to update on my channel?
Thanks,
John

---------- Forwarded message ---------
From: Roku Developers Service Notice ***@***.***>
Date: Mon, Dec 16, 2024 at 5:55 AM
Subject: Action Required: Migrate to Widevine DRM by June 30, 2025
To: ***@***.***>


You are receiving this email because you have one more apps that use
PlayReady DRM for content protection.
͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌
  ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏
‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌
﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌
    ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿
͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌
  ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏
‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌
﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌
    ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿
͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌
  ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏
‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌     ﻿ ͏ ‌
﻿ ͏ ‌     ﻿
  ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏
‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌
͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌
  ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏
‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌
͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌
  ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏
‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏
‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌
͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌
  ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏
‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌
͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌
  ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏
‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌
͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌
  ‌   ͏ ‌   ͏ ‌  ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌   ͏ ‌
  ͏ ‌   ͏
[image: Roku Developers]
<https://link.p.email.roku.com/ss/c/u001.vIdyUrsxEEVGu2Gjhe7_X9g-l8bA3He-WmSrKBRxgeM6cQhpJaumRmvT51PRbeEmYlVKZNhWFURqHBVwsILrd12LpJLvfWC55CQcPyZYWhyKAqDeqeGQWxRRQzs26eq3gNqIDAN_4sRc8iVJTvAnY5ouvnmFWEGWBsNpr67-oKBoU463sUjmWF6MY6O6LuRfZGmcR-gzP4_1FwnL8TSOMwGTauWoWQqzlQfsaldI8vc/4cc/Ywtz5_9rRtam519uiIYDGQ/h9/h001.vvw2I8gHCdF_BDbnQDU0pHXIB9QRy7ZgBf47D9t7tAg>

Hi John,

You are receiving this email because you have one more apps that use
PlayReady DRM for content protection. Roku will be ending support for
PlayReady DRM in the United States, Canada, and Latin America in the near
future. To ensure uninterrupted service for your customers, you should
migrate your app's content protection to Widevine DRM by *June 30, 2025*.

For more information on why Roku will soon be requiring app to use Widevine
DRM, please click here
<https://link.p.email.roku.com/ss/c/u001.mRW_jLLY3vxV6ckQnlshz0Azlib_fPnWHLnIzqMJrJ-WtzRp09uXIYG0vns13_5f3P64lD4JNUMEUZBrLx_89LMlRB4C5p1qsP4QCE5kU57be6YK2nZ9TLF3vhNz7bX7BZCfljn30CQVDaq7A-revHp13vpCglKDvXyJ_xJ-KlCH_coEKaqMWaPtMm5pbR6CT0Iwi99dtk5PsTYjGmOEQqZo1__Awpf_Z29zgqIXLBM/4cc/Ywtz5_9rRtam519uiIYDGQ/h10/h001.yAvqKLOcLkycH0DxOu7slyl5IEulyL57pNcH5nqd0k0>
.

If you have any technical questions about this migration, contact Roku
Partner Success
<https://link.p.email.roku.com/ss/c/u001.vIdyUrsxEEVGu2Gjhe7_X9g-l8bA3He-WmSrKBRxgeOxxxfqh70LKp1NiFWcCQwVq38LeTDkFIO4-1B_DX1MkeTbNUm__GphKkkt0nI6JPzRdSFiy2xPCjsERYyYw4C0Ng51sSyfDbtY1pf4DxKh9Tqh54vuxAokS32GvLtltF_xnfwPXzzIUGlVJtSYluxKWIcifOKFPv-gixgo85ponQ/4cc/Ywtz5_9rRtam519uiIYDGQ/h11/h001.vB7XQLsk9GX2z3HKaiNJY0CrWlfSu19mW-F56VLvZUA>
and select the *Video Streaming* topic under Technical Issues.

Thanks,
Roku
[image: Roku]
<https://link.p.email.roku.com/ss/c/u001.AvB4i5M6YDGYWiFzNBDMKS7NbuwXe3y9abcbL6sXziGlElsUr6QPc8qRH3DDyAcEWVRzPRtoTwTcMPDYo1Qvhj53vAeMEyiGQCuSQ-dEqoVrD2TSFPLrYK1O7TRA1Rq4OnpMd_NjsLgSdz55-_yi50Pq9vdF31d4wlhS6PK4Xu34l3O6R_q6tcXry3rt96A2iWTrjmDnPe8NHBfi_BEd1w/4cc/Ywtz5_9rRtam519uiIYDGQ/h12/h001.3POWtwIZfBZW12XBNSFJpVD5fxy3usVom8F7ml6AU30>

Shop Now
<https://link.p.email.roku.com/ss/c/u001.AvB4i5M6YDGYWiFzNBDMKVnXVusOCHw7t_8PP3LAmFFBVbP0THYHT1ckcgEqNiJecxnzZxKR1EymL8wH9J9pmvUK-3OX8kgBpIildNlfRh-dIfC1ThMgcI0uVIdTcXMsOhC3VnzCctQhlRUiEV-HwTFSHJ7Sft_eAtxk8EEB4Y8W-nnDAHtEdqncrIV7uHvDbhD5_fm6P-_FlA19eQumNA/4cc/Ywtz5_9rRtam519uiIYDGQ/h13/h001.1VXwXaCo4kmIf_Vk6AFFjIJjoQ08VdpsYEOPJUJDo8w>
  |   Get the App
<https://link.p.email.roku.com/ss/c/u001.AvB4i5M6YDGYWiFzNBDMKWZdxuVYuG80QJU-iLx8v7EKnb1H0RnZ9b_l9fFQV3xzJL1SFdFe_tNphd7oYcWq_DyXL2BNYH4waauqGiHOcrr763fQZ71AztViGB5dXNCebkNnzn751O7i-0v2Kwl6gyLLwEV8l21EGKnpCYwysEXRoTzcfZQ65d5J5oZBRBwg4paRcEcZA2CHJqOB-RLiKA/4cc/Ywtz5_9rRtam519uiIYDGQ/h14/h001.X2p1qCeCVS6H318pwwfrHHU_u26iwdmyLG5yndA0584>
  |   Blog
<https://link.p.email.roku.com/ss/c/u001.mRW_jLLY3vxV6ckQnlshz0Azlib_fPnWHLnIzqMJrJ83R-DowjAjpuBALM0d4oVBAxBetDZ2JFQEKCQFeLLSumRdvHfbyeEWPcHK0FIBbItR2f_mcR__BoJECEd0nsk9XLarMCAv6FuXrFuhrfmYPq_M2KAt8ygg78deuigUu11coup1SxwbxtNCkoclxW0W2Oz9mj0pyxKnN5czrYHPiw/4cc/Ywtz5_9rRtam519uiIYDGQ/h15/h001.nFuo6iRzbt7KNGnC5Fsxx5STW8G9v6XaGycDhLo2H4c>
 |
Support
<https://link.p.email.roku.com/ss/c/u001.T1c3Wyae73rr_J488W467vUwo1lEmwOcRXKCxr2oNZg6k9dmfrJ4hFdEe2Yuclz1AKupKAdX30zoWblFVQNGKgRW9IzjrLLNahyNCqzKA0YTPi-YJ1jCxtxj9zTD0VHGcmapL8BccXePeMAa6PR4p9-wIjaZhylAev5kIpN6vSqJK13lkbvp89Sl2wgi2KOvOu_qKyjWGhu_ogOJXCWi_w/4cc/Ywtz5_9rRtam519uiIYDGQ/h16/h001.L2QcZloFn5-SkKxH2IrNHS00Jb_hd7S2d-rkxtLvkWA>
  |   Privacy Policy
<https://link.p.email.roku.com/ss/c/u001.vIdyUrsxEEVGu2Gjhe7_X7KYXboMc6fyMDQ-QsrSGeevgc6MxuOpw7rK_og7uclRsfvR3K1k5p8ZibhM9aH5Y6Qmh6LyC-huc3mkanYQnmZkL-mECUtCu4f21HlLi8te7XBO0E_H6_X5yBXTpq-Kljxz1iEChBtbAK2NoFVNPACXZRlz7456yl4ZZHgzcEl-QxPBW2-KRbs-dztMdDWE7bIbTpH4Jg3XzoRxX5_PaMt87Y-iuqi-HnZ8gp19G4WJ/4cc/Ywtz5_9rRtam519uiIYDGQ/h17/h001.CfK6AYVEcuY3c8ymjE467NAewhWNa0bFmQ1i-KvLAnI>

© 2024 Roku Inc. All rights reserved. ROKU, the ROKU logo, the purple
fabric tag, the purple d-pad, ROKU TV, and "HAPPY STREAMING" are trademarks
or registered trademarks of Roku, Inc. All other trademarks are the
property of their respective owners.

This email was sent to ***@***.*** <#m_4449713064379055879_> by
Roku, Inc., 1173 Coleman Ave. San Jose CA 95110. <#m_4449713064379055879_>


-- 
Blessings,
John Locke
https://JLNbroadcasting.com

**Comment by JLNjolo** [comment]
OK.
________________________________
