### ISSUE TITLE
background missing

### ISSUE THREAD

**Issue by AndrewRCD** [rrirower/DP2SceneGraphWizard#96]
H I just installed the new version beta 5

but I cannot make it show the background image I uploaded only a color. What am I doing wrong? 

form the manifest 

splash_color=#8A2BE2
BACKGROUND_COLOR=#8A2BE2
ui_resolutions=hd
USE_RAF=0
OFFER_SUBSCRIPTIONS=0
supports_input_launch=1
mm_icon_focus_hd=pkg:/images/channel.png
splash_screen_hd=pkg:/images/splash.png
OVERHANG=pkg:/images/overhang.png
BACKGROUND_IMAGE=pkg:/images/background.png

but the channel shows as the image 
![dev](https://github.com/rrirower/DP2SceneGraphWizard/assets/161251722/fb3157e0-5c16-472b-828d-232d29f1e85e)

**Comment by rrirower** [comment]
Open the zip file and look in the images folder. Is there an image file with the same name as the manifest indicates?

**Comment by AndrewRCD** [comment]
yes it is  - and i tried both formats - for some reason - jpg and png  - none of them works.

**Comment by rrirower** [comment]
I'll have to try it on my end.

**Comment by AndrewRCD** [comment]
thank you

**Comment by rrirower** [comment]
Can you post the image you're using for a background?

**Comment by AndrewRCD** [comment]
of course 
![background](https://github.com/rrirower/DP2SceneGraphWizard/assets/161251722/e2f4520d-1a26-4f6d-aad4-8e1d1b142f05)
![background](https://github.com/rrirower/DP2SceneGraphWizard/assets/161251722/37475500-8786-434c-a800-e2f44cca9923)

**Comment by rrirower** [comment]
Sorry, I meant it as an attachment so I can test with it.

**Comment by AndrewRCD** [comment]
![background](https://github.com/rrirower/DP2SceneGraphWizard/assets/161251722/e312bccd-cd60-4200-9677-f5632181cf98)

**Comment by AndrewRCD** [comment]
also tried this 2 
![background (2)](https://github.com/rrirower/DP2SceneGraphWizard/assets/161251722/0d6b7950-36e5-4b5d-bf16-bdbe1a29c36e)
![background](https://github.com/rrirower/DP2SceneGraphWizard/assets/161251722/f016705e-48c7-4598-bbdd-39b55b849bf7)

**Comment by rrirower** [comment]
Two issues here.

1. There was a regression bug that broke some previously working code.  It is fixed.
2. Your image size is incorrect.  Roku has some strict requirements regarding images.  Please try using 1280x720 for your background image.  It should work.

I've reposted the beta.5 code, so, you'll need to re-run the wizard to rebuild your zip file.  Let me know if this resolves your issue.

**Comment by AndrewRCD** [comment]
perfect - thank you
