### ISSUE TITLE
Capitalization change in Season list once it is highlighted and moved from

### ISSUE THREAD

**Issue by jsonnentag** [rrirower/DP2SceneGraphWizard#97]
This is mostly just annoying as far as aesthetics goes and I'm sure simple to change if you know exactly what line to modify that does the "rewrite when going from highlighted to not highlighted".

When viewing Seasons in a series they all start out capitalized (I have Seasons 2020 through 2024), but once you browse the seasons and scroll through them once they aren't highlighted anymore the "S" in Season changes to "s".

**Comment by rrirower** [comment]
Please provide an image showing this issue.

**Comment by jsonnentag** [comment]
This is what it looks like for the Seasons list (far left side) before any highlighting or scrolling through them;
![dev](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/050b2993-1634-482c-a310-2064463a1774)


This is what the Seasons list looks like after 3 have been scrolled through (capital "S" becomes lowercase "s" on everything scrolled past):
![dev](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/579155b0-46ef-4d56-9de2-50e66bae7d88)

**Comment by rrirower** [comment]
This is a bug and should be resolved in the next release.

**Comment by rrirower** [comment]
Resolved in version 1.0.0.1.
